// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Account
{
    public Guid AccountId { get; set; }

    public string AccountName { get; set; }

    public DateTime? NetworkLastUpload { get; set; }

    public DateTime? NetworkLastDownload { get; set; }

    public string AccountDescription { get; set; }

    public string Code { get; set; }

    public string Network { get; set; }

    public string Domain { get; set; }

    public bool? PlayerIdentityCodeRequired { get; set; }

    public bool? PlayerEmailRequired { get; set; }

    public int? MembershipCardAutoPrint { get; set; }

    public Guid? MembershipCardReportId { get; set; }

    public int? CardFieldLength { get; set; }

    public string CardFieldSeparator { get; set; }

    public int? CardParseType { get; set; }

    public int? CardFieldPosition { get; set; }

    public string MembershipCardFormat { get; set; }

    public bool? PlayerCardNumberRequired { get; set; }

    public int? MembershipCardNumberLength { get; set; }

    public string CardFormula { get; set; }

    public string SmsProviderName { get; set; }

    public byte[] SmsProviderData { get; set; }

    public string MailProviderName { get; set; }

    public byte[] MailProviderData { get; set; }

    public bool? PlayerDefaultPrivacyAgree { get; set; }

    public bool? PlayerDocumentVerifiedRequired { get; set; }

    public bool? MembershipCardAutoGenerate { get; set; }

    public bool? PlayerCountryRequired { get; set; }

    public string IntegrationProviderName { get; set; }

    public byte[] IntegrationProviderData { get; set; }

    public Guid? WaiverDocumentId { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}