// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Article
{
    public Guid ArticleId { get; set; }

    public string ArticleDescription { get; set; }

    public Guid? ArticleFamilyId { get; set; }

    public string Code { get; set; }

    public double? TaxRate { get; set; }

    public string MeasureUnit { get; set; }

    public double? PreviousCost { get; set; }

    public double? LastCost { get; set; }

    public double? AverageCost { get; set; }

    public double? AveragePrice { get; set; }

    public bool Cancelled { get; set; }

    public string Ean { get; set; }

    public double? Price { get; set; }

    public byte[] Image { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ArticleFamily ArticleFamily { get; set; }
}