// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class ArticleFamily
{
    public Guid ArticleFamilyId { get; set; }

    public string ArticleFamilyDescription { get; set; }

    public Guid? ParentId { get; set; }

    public byte[] Image { get; set; }

    public string Path { get; set; }

    public bool? Cancelled { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();
}