// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class AttachmentType
{
    public Guid AttachmentTypeId { get; set; }

    public string Description { get; set; }

    public int? FileType { get; set; }

    public bool? Reserved { get; set; }

    public bool? Hidden { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<Attachment> Attachments { get; set; } = new List<Attachment>();
}