// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class BlackListPlayer
{
    public Guid BlackListPlayerId { get; set; }

    public Guid? BlackListId { get; set; }

    public string Account { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public DateTime? BirthDate { get; set; }

    public string Email { get; set; }

    public string NormalizedLastname { get; set; }

    public string NormalizedFirstname { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual BlackList BlackList { get; set; }
}