// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashSession
{
    public Guid CashSessionId { get; set; }

    public int? Code { get; set; }

    public DateTime? Date { get; set; }

    public DateTimeOffset? BeginDate { get; set; }

    public DateTimeOffset? EndDate { get; set; }

    public int? LastTicketNumber { get; set; }

    public int? Status { get; set; }

    public Guid? SeasonId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public double? TotalRake { get; set; }

    public double? TotalMinutesPlayed { get; set; }

    public int? TotalPlayers { get; set; }

    public Guid? PromotionId { get; set; }

    public DateTime? LastUpdated { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<CashPlayerBreak> CashPlayerBreaks { get; set; } = new List<CashPlayerBreak>();

    public virtual ICollection<CashPlayerChip> CashPlayerChips { get; set; } = new List<CashPlayerChip>();

    public virtual ICollection<CashPlayerStack> CashPlayerStacks { get; set; } = new List<CashPlayerStack>();

    public virtual ICollection<CashPlayerTip> CashPlayerTips { get; set; } = new List<CashPlayerTip>();

    public virtual ICollection<CashPlayer> CashPlayers { get; set; } = new List<CashPlayer>();

    public virtual ICollection<CashTable> CashTables { get; set; } = new List<CashTable>();

    public virtual ICollection<CashWaitingList> CashWaitingLists { get; set; } = new List<CashWaitingList>();
}