// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashTable
{
    public Guid CashTableId { get; set; }

    public Guid CashSessionId { get; set; }

    public Guid? CashTypeId { get; set; }

    public int? Index { get; set; }

    public int? Status { get; set; }

    public double? Rake { get; set; }

    public DateTimeOffset? OpenDate { get; set; }

    public DateTimeOffset? ActivateDate { get; set; }

    public DateTimeOffset? CloseDate { get; set; }

    public Guid? DeviceId { get; set; }

    public DateTime? RakeRequestedOn { get; set; }

    public DateTime? RakeExpiration { get; set; }

    public DateTimeOffset? RequestStackDate { get; set; }

    public DateTimeOffset? RequestStaffDate { get; set; }

    public DateTimeOffset? RequestBarDate { get; set; }

    public decimal? TotalStackAmount { get; set; }

    public decimal? TotalRakePerHandAmount { get; set; }

    public decimal? TotalPotPerHandAmount { get; set; }

    public int? TotalEntries { get; set; }

    public int? TotalHands { get; set; }

    public byte[] SeatsData { get; set; }

    public string Note { get; set; }

    public Guid? ClubRoomId { get; set; }

    public decimal? TotalTipAmount { get; set; }

    public decimal? Tips { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual CashSession CashSession { get; set; }
}