// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashSessionType
{
    public Guid CashSessionId { get; set; }

    public Guid CashTypeId { get; set; }

    public int? Status { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}