// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashPlayer
{
    public Guid CashPlayerId { get; set; }

    public Guid? CashSessionId { get; set; }

    public Guid? CashTableId { get; set; }

    public int? CashTableIndex { get; set; }

    public int? CashTableSitIndex { get; set; }

    public long? Ticket { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public Guid? PlayerId { get; set; }

    public DateTimeOffset? SubscriptionDate { get; set; }

    public DateTimeOffset? CheckinDate { get; set; }

    public DateTimeOffset? CheckoutDate { get; set; }

    public long? InactivityTicks { get; set; }

    public Guid? PlayedCashTypeId { get; set; }

    public int? Status { get; set; }

    public double? TotalMinutesPlayed { get; set; }

    public Guid? SubscriptionUserId { get; set; }

    public string Note { get; set; }

    public bool? AllowMessageNotification { get; set; }

    public DateTimeOffset? RakeRequestedOn { get; set; }

    public DateTime? RakeExpiration { get; set; }

    public DateTime? RakePaymentDate { get; set; }

    public int? HandsPlayed { get; set; }

    public long? HandsPlayedTicks { get; set; }

    public int? RakeMinutes { get; set; }

    public decimal? RakeAmount { get; set; }

    public decimal? RakeTotalPaidAmount { get; set; }

    public double? TotalMinutesBreak { get; set; }

    public decimal? StackTotalAmount { get; set; }

    public decimal? StackTotalPaid { get; set; }

    public decimal? TipTotalAmount { get; set; }

    public decimal? TipTotalPaid { get; set; }

    public decimal? CashOutTotalAmount { get; set; }

    public Guid? PlayedTableId { get; set; }

    public int? RakeCount { get; set; }

    public decimal? RakeTotalDue { get; set; }

    public decimal? RakeTotalAmount { get; set; }

    public decimal? RakeElapsedTotalMinutes { get; set; }

    public Guid? PlayerCardTypeId { get; set; }

    public bool? RakeExcludeInactivityTime { get; set; }

    public Guid? DomainTicketId { get; set; }

    public DateTimeOffset? ShowUpDate { get; set; }

    public decimal? ChipsOutAmount { get; set; }

    public int? GameFlags { get; set; }

    public decimal? ChipsInAmount { get; set; }

    public DateTimeOffset? LastUpdated { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual CashSession CashSession { get; set; }
}