// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashTypeRake
{
    public Guid CashTypeRakeId { get; set; }

    public Guid? CashTypeId { get; set; }

    public decimal? PotAmount { get; set; }

    public decimal? Value { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual CashType CashType { get; set; }
}