// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashPlayerBreak
{
    public Guid CashPlayerBreakId { get; set; }

    public Guid? CashSessionId { get; set; }

    public Guid? CashPlayerId { get; set; }

    public DateTimeOffset? BeginDate { get; set; }

    public DateTimeOffset? EndDate { get; set; }

    public Guid? UserId { get; set; }

    public int? TotalMinutes { get; set; }

    public int? Type { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual CashSession CashSession { get; set; }
}