// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashPlayerTip
{
    public Guid CashPlayerTipId { get; set; }

    public Guid? CashPlayerId { get; set; }

    public Guid? UserId { get; set; }

    public decimal? Amount { get; set; }

    public Guid? CashTypeId { get; set; }

    public Guid? CashSessionId { get; set; }

    public DateTimeOffset? Date { get; set; }

    public decimal? PaidAmount { get; set; }

    public string Note { get; set; }

    public Guid? DealerId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual CashSession CashSession { get; set; }
}