// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashHand
{
    public Guid CashHandId { get; set; }

    public Guid? CashSessionId { get; set; }

    public Guid? CashTypeId { get; set; }

    public DateTime? BeginDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? EndDateOfPrevious { get; set; }

    public int? EndStatus { get; set; }

    public Guid? UserId { get; set; }

    public int? TableIndex { get; set; }

    public decimal? TotalPot { get; set; }

    public decimal? TotalRake { get; set; }

    public Guid? DeviceId { get; set; }

    public Guid? CashTableId { get; set; }

    public int? Number { get; set; }

    public int? TotalPotCount { get; set; }

    public int? TotalPlayerCount { get; set; }

    public int? TotalIngamePlayerCount { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<CashHandPlayer> CashHandPlayers { get; set; } = new List<CashHandPlayer>();
}