// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashHandPlayer
{
    public Guid CashHandPlayerId { get; set; }

    public Guid? CashHandId { get; set; }

    public Guid? CashPlayerId { get; set; }

    public int? TableSeatIndex { get; set; }

    public int? Status { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual CashHand CashHand { get; set; }
}