// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashWaitingList
{
    public Guid CashWaitingListId { get; set; }

    public Guid? CashSessionId { get; set; }

    public Guid? CashTypeId { get; set; }

    public Guid? PlayerId { get; set; }

    public int? Index { get; set; }

    public DateTimeOffset? StartDate { get; set; }

    public int? CallCount { get; set; }

    public bool IsWaiting { get; set; }

    public DateTime? LastNotificationDate { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public DateTime? BirthDate { get; set; }

    public Guid? CountryId { get; set; }

    public string Nickname { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Number { get; set; }

    public string Note { get; set; }

    public string LiPokerCardId { get; set; }

    public Guid? DomainTicketId { get; set; }

    public Guid? DomainId { get; set; }

    public DateTimeOffset? SubscriptionDate { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual CashSession CashSession { get; set; }
}