// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashType
{
    public Guid CashTypeId { get; set; }

    public Guid? GameTypeId { get; set; }

    public double? SmallBlind { get; set; }

    public double? BigBlind { get; set; }

    public int? SitCount { get; set; }

    public int? MaxWaitingMinutes { get; set; }

    public int? MaxCallCount { get; set; }

    public int? ShiftMethods { get; set; }

    public Guid? PromotionId { get; set; }

    public decimal? MinBuyin { get; set; }

    public decimal? MaxBuyin { get; set; }

    public double? Straddle { get; set; }

    public double? Ante { get; set; }

    public bool? AllowNoRake { get; set; }

    public bool? RequireBoardStatus { get; set; }

    public decimal? RakePercentage { get; set; }

    public decimal? RakeAmountCap { get; set; }

    public int? RakeRoundType { get; set; }

    public decimal? RakeRoundValue { get; set; }

    public int? RakeType { get; set; }

    public int? Color { get; set; }

    public int? NotificationType { get; set; }

    public decimal? RakeValue { get; set; }

    public double? BringIn { get; set; }

    public string Description { get; set; }

    public string ShortDescription { get; set; }

    public double? Limit1 { get; set; }

    public double? Limit2 { get; set; }

    public int? RakeValueType { get; set; }

    public decimal? RakeTimedAmount { get; set; }

    public int? RakeTimedMinutes { get; set; }

    public int? WaitingListGroup { get; set; }

    public bool? AllowHandRecording { get; set; }

    public Guid? ClubId { get; set; }

    public bool? LiveHidden { get; set; }

    public int? LiveRegistrationType { get; set; }

    public string Note { get; set; }

    public string Promotion { get; set; }

    public bool? NoFlopNoRake { get; set; }

    public bool? WaitingListHidden { get; set; }

    public bool? RakeExcludeInactivityTime { get; set; }

    public int? WaitingListOrderIndex { get; set; }

    public bool? LiveSelfRegistrationAllowed { get; set; }

    public int? ShowUpMaxMinutes { get; set; }

    public bool? RequireChipsRecording { get; set; }

    public int? LongBreakMaxMinutes { get; set; }

    public int? StandardBreakMaxMinutes { get; set; }

    public Guid? CurrencyId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<CashTypeRake> CashTypeRakes { get; set; } = new List<CashTypeRake>();
}