// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashRake
{
    public Guid CashRakeId { get; set; }

    public Guid? CashSessionId { get; set; }

    public Guid? CashPlayerId { get; set; }

    public Guid? CashTypeId { get; set; }

    public DateTimeOffset? Date { get; set; }

    public decimal? PotAmount { get; set; }

    public decimal? RakeAmount { get; set; }

    public Guid? CashHandId { get; set; }

    public Guid? CashTableId { get; set; }

    public Guid? UserId { get; set; }

    public int? Type { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}