// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CashPlayerChip
{
    public Guid CashPlayerChipsId { get; set; }

    public Guid? CashSessionId { get; set; }

    public Guid? CashPlayerId { get; set; }

    public DateTimeOffset? Date { get; set; }

    public decimal? Amount { get; set; }

    public Guid? UserId { get; set; }

    public virtual CashSession CashSession { get; set; }
}