// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Causal
{
    public Guid CausalId { get; set; }

    public string CausalDescription { get; set; }

    public int? CausalActionType { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}