// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class ClubRoom
{
    public Guid ClubRoomId { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubRoomDescription { get; set; }

    public byte[] ImageContent { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Club Club { get; set; }
}