// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Club
{
    public Guid ClubId { get; set; }

    public string ClubDescription { get; set; }

    public byte[] Logo { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string ZipCode { get; set; }

    public string State { get; set; }

    public Guid? CountryId { get; set; }

    public string Email { get; set; }

    public string WebSite { get; set; }

    public string TaxCode { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public Guid? CurrencyId { get; set; }

    public bool? UseWindowsKeyboard { get; set; }

    public DateTime? NetworkLastUpdate { get; set; }

    public bool? AllowEventRebuyAddon { get; set; }

    public bool? PlayerIdentityCodeRequired { get; set; }

    public bool? PlayerCardNumberRequired { get; set; }

    public bool? EventTemplateRequired { get; set; }

    public string EventPointFormula { get; set; }

    public Guid? CashReportId { get; set; }

    public bool? CashTouchScreenPrintTicket { get; set; }

    public int? CashTouchScreenTimeout { get; set; }

    public Guid? TournamentReportId { get; set; }

    public Guid? TournamentPayoutId { get; set; }

    public Guid? SitngoPayoutId { get; set; }

    public int? CardParseType { get; set; }

    public int? CardFieldPosition { get; set; }

    public int? CardFieldLength { get; set; }

    public string CardFieldSeparator { get; set; }

    public int? MembershipCardAutoPrint { get; set; }

    public Guid? MembershipCardReportId { get; set; }

    public string Account { get; set; }

    public string Domain { get; set; }

    public string Network { get; set; }

    public string IntegrationProviderName { get; set; }

    public byte[] IntegrationProviderData { get; set; }

    public bool? PlayerEmailRequired { get; set; }

    public DateTime? NetworkLastUpload { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string WebSiteName { get; set; }

    public string TwitterName { get; set; }

    public string FacebookName { get; set; }

    public byte[] BannerContent { get; set; }

    public string WebSiteSkinName { get; set; }

    public Guid? TournamentPaymentModalityId { get; set; }

    public bool? TournamentPayoutAutoAssignment { get; set; }

    public Guid? TournamentPayoutReportId { get; set; }

    public bool? TournamentAllowSubscriptionForEachDay { get; set; }

    public Guid? TournamentRebuyAddonReportId { get; set; }

    public Guid? TournamentWaitingReportId { get; set; }

    public int? TournamentPublishingFlag { get; set; }

    public DateTime? NetworkLastDownload { get; set; }

    public double? ProfitTaxPercentage { get; set; }

    public string CashSmsDefaultTemplate { get; set; }

    public string SmsProviderName { get; set; }

    public byte[] SmsProviderData { get; set; }

    public string TournamentSmsDefaultTemplate { get; set; }

    public Guid? CashRakePaymentModalityId { get; set; }

    public bool? CashTouchScreenAllowCheckin { get; set; }

    public Guid? CashStackReportId { get; set; }

    public Guid? TournamentReservationReportId { get; set; }

    public Guid? ServerId { get; set; }

    public string Code { get; set; }

    public string LocationName { get; set; }

    public string LocationDescription { get; set; }

    public decimal? LocationLongitude { get; set; }

    public decimal? LocationLatitude { get; set; }

    public string LocationTimeZoneId { get; set; }

    public string CardFormula { get; set; }

    public int? TablesCount { get; set; }

    public int? RequiredAge { get; set; }

    public string Announcements { get; set; }

    public int? LocationType { get; set; }

    public bool? LiPokerEnabled { get; set; }

    public bool? LiPokerCashStakesVisible { get; set; }

    public bool? LiPokerCashWaitingListRegistrationAllowed { get; set; }

    public decimal? LiPokerRegWaitingListMaxDistance { get; set; }

    public bool? LiPokerTournamentVisible { get; set; }

    public bool? LiPokerTournamentRegistrationAllowed { get; set; }

    public string LocationOpeningTime { get; set; }

    public string LocationFeatures { get; set; }

    public byte[] LiPokerBanner { get; set; }

    public string MailProviderName { get; set; }

    public byte[] MailProviderData { get; set; }

    public decimal? PlayerLimitAmountMonthly { get; set; }

    public decimal? PlayerLimitAmountWeekly { get; set; }

    public decimal? PlayerLimitAmountDaily { get; set; }

    public decimal? CashTimeCostAmountPerHour { get; set; }

    public Guid? TournamentBonusTicketReportId { get; set; }

    public Guid? TournamentPayoutTicketReportId { get; set; }

    public Guid? TournamentPlayerSeatReportId { get; set; }

    public Guid? TournamentPlayerEliminationReportId { get; set; }

    public Guid? TournamentPlayerUnsubscribeReportId { get; set; }

    public bool? PlayerDocumentRequired { get; set; }

    public string CashCheckInNotificationTemplate { get; set; }

    public Guid? WaiverDocumentId { get; set; }

    public bool? CashTouchSitoutSelfRegistered { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<ClubRoom> ClubRooms { get; set; } = new List<ClubRoom>();

    public virtual ICollection<PlayerClub> PlayerClubs { get; set; } = new List<PlayerClub>();

    public virtual ICollection<UserPerClub> UserPerClubs { get; set; } = new List<UserPerClub>();
}