// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Country
{
    public Guid CountryId { get; set; }

    public string CountryDescription { get; set; }

    public byte[] Flag { get; set; }

    public string Code { get; set; }

    public string CodeExt { get; set; }

    public string Number { get; set; }

    public byte[] Flag16 { get; set; }

    public string Nationality { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}