// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Currency
{
    public Guid CurrencyId { get; set; }

    public string CurrencyDescription { get; set; }

    public string Symbol { get; set; }

    public string Code { get; set; }

    public decimal? Usdmultiplier { get; set; }

    public string CurrencyName { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}