// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class CustomProperty
{
    public Guid CustomPropertyId { get; set; }

    public string Name { get; set; }

    public string Group { get; set; }

    public int? Type { get; set; }

    public byte[] Value { get; set; }

    public string CustomPropertyDescription { get; set; }

    public bool? Visible { get; set; }

    public int? OrderIndex { get; set; }

    public Guid? VenueId { get; set; }

    public Guid? ServerId { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}