// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class DocumentType
{
    public Guid DocumentTypeId { get; set; }

    public string DocumentTypeDescription { get; set; }

    public Guid? CausalId { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}