// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class DocumentDetail
{
    public Guid DocumentDetailId { get; set; }

    public Guid? DocumentId { get; set; }

    public Guid? ArticleId { get; set; }

    public string ArticleCode { get; set; }

    public string ArticleDescription { get; set; }

    public double? Quantity { get; set; }

    public double? UnitPrice { get; set; }

    public double? TotalPrice { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Document Document { get; set; }
}