// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class DocumentTemplate
{
    public Guid DocumentTemplateId { get; set; }

    public string DocumentTemplateDescription { get; set; }

    public byte[] Content { get; set; }

    public Guid? ClubId { get; set; }

    public byte[] ExtraData { get; set; }

    public int? ExpirationDays { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}