// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Domain
{
    public Guid DomainId { get; set; }

    public string DomainDescription { get; set; }

    public bool? AllowUpdateMembershipProfile { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<DomainCloudMessage> DomainCloudMessages { get; set; } = new List<DomainCloudMessage>();

    public virtual ICollection<DomainPlayerTicket> DomainPlayerTickets { get; set; } = new List<DomainPlayerTicket>();

    public virtual ICollection<PlayerDomain> PlayerDomains { get; set; } = new List<PlayerDomain>();
}