// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class DomainCloudMessage
{
    public Guid DomainCloudMessageId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public int? Status { get; set; }

    public string Error { get; set; }

    public Guid? ServerId { get; set; }

    public Guid? UserId { get; set; }

    public DateTime? CreationDate { get; set; }

    public DateTime? StatusDate { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ClubId { get; set; }

    public string ReferenceDescription { get; set; }

    public Guid? DomainId { get; set; }

    public Guid? PlayerId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Domain Domain { get; set; }
}