// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class DomainEntityChange
{
    public Guid DomainEntityChangeId { get; set; }

    public int? Type { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public Guid? ReferenceId { get; set; }

    public string Description { get; set; }

    public Guid? ClubId { get; set; }

    public Guid? DomainId { get; set; }

    public Guid? LeagueId { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? LastUpdated { get; set; }
}