// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class EntityChange
{
    public Guid Id { get; set; }

    public Guid? EntityId { get; set; }

    public DateTime? Date { get; set; }

    public string Description { get; set; }

    public int? Type { get; set; }
}