// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Entity
{
    public Guid EntityId { get; set; }

    public string EntityName { get; set; }

    public string TypeProvider { get; set; }

    public string DataProvider { get; set; }

    public Guid? DefaultViewId { get; set; }
}