// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Feature
{
    public Guid FeatureId { get; set; }

    public Guid? FeatureGroupId { get; set; }

    public string FeatureKey { get; set; }

    public int? PermissionFlags { get; set; }

    public string FeatureDescription { get; set; }
}