// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class GameType
{
    public Guid GameTypeId { get; set; }

    public string GameTypeDescription { get; set; }

    public int? LimitTypeId { get; set; }

    public string Name { get; set; }

    public int? CategoryId { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}