// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Group
{
    public Guid GroupId { get; set; }

    public string GroupDescription { get; set; }

    public bool System { get; set; }

    public bool Reserved { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();
}