// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Localization
{
    public Guid Id { get; set; }

    public string Language { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }
}