// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class LocationFeature
{
    public Guid LocationFeatureId { get; set; }

    public string Description { get; set; }

    public string Key { get; set; }

    public int? OrderIndex { get; set; }
}