// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Lock
{
    public string ItemName { get; set; }

    public Guid ItemId { get; set; }

    public DateTime Date { get; set; }

    public Guid UserId { get; set; }

    public string Username { get; set; }

    public string Hostname { get; set; }
}