// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class MailRecipient
{
    public Guid MailRecipientId { get; set; }

    public Guid MailId { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? Delivery { get; set; }

    public string Recipient { get; set; }

    public int? Messages { get; set; }

    public int? Result { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public string ReferenceDescription { get; set; }

    public double? TotalCredit { get; set; }

    public byte[] Timestamp { get; set; }

    public string ErrorMessage { get; set; }

    public string Identifier { get; set; }

    public string ProviderName { get; set; }

    public string ErrorCode { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Mail Mail { get; set; }
}