// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class MarketingTemplate
{
    public Guid MarketingTemplateId { get; set; }

    public string MarketingTemplateDescription { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public Guid? EntityReferenceId { get; set; }

    public int? MarketingTemplateType { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}