// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class MembershipCardType
{
    public Guid MembershipCardTypeId { get; set; }

    public string MembershipCardTypeDescription { get; set; }

    public decimal? AffiliationFee { get; set; }

    public int? AffiliationPeriodType { get; set; }

    public int? AffiliationPeriod { get; set; }

    public string Code { get; set; }

    public int? Color { get; set; }

    public Guid? PromotionId { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}