// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class MembershipAffiliation
{
    public Guid MembershipAffiliationId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public Guid? MembershipCardTypeId { get; set; }

    public decimal? TotalFeeAmount { get; set; }

    public decimal? TotalPaidFeeAmount { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? UserId { get; set; }

    public DateTime? CreationDate { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}