// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class MenuLink
{
    public Guid MenuId { get; set; }

    public Guid MenuItemId { get; set; }

    public int? Position { get; set; }

    public string Method { get; set; }

    public string Arguments { get; set; }

    public virtual Menu Menu { get; set; }
}