// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Menu
{
    public Guid MenuId { get; set; }

    public Guid? ParentId { get; set; }

    public string DefaultDescription { get; set; }

    public string DefaultImage { get; set; }

    public int? Position { get; set; }

    public string Modules { get; set; }

    public virtual ICollection<MenuLink> MenuLinks { get; set; } = new List<MenuLink>();
}