// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class OlapviewColumn
{
    public Guid OlapviewColumnId { get; set; }

    public Guid? OlapviewId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string FieldName { get; set; }

    public string FormatString { get; set; }

    public bool? Visible { get; set; }

    public bool? Unbound { get; set; }

    public byte[] Options { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Olapview Olapview { get; set; }
}