// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Olapview
{
    public Guid OlapviewId { get; set; }

    public string Description { get; set; }

    public string Name { get; set; }

    public string GroupName { get; set; }

    public string QueryString { get; set; }

    public string Modules { get; set; }

    public bool? System { get; set; }

    public string Comments { get; set; }

    public string Entities { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<OlapviewColumn> OlapviewColumns { get; set; } = new List<OlapviewColumn>();
}