// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class PaymentType
{
    public Guid PaymentTypeId { get; set; }

    public string PaymentTypeDescription { get; set; }

    public string Code { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}