// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class PaymentModalityPerPlayer
{
    public Guid PaymentModalityPerPlayerId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? PaymentModalityId { get; set; }

    public DateTimeOffset? CreationDate { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual PaymentModality PaymentModality { get; set; }

    public virtual Player Player { get; set; }
}