// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Permission
{
    public Guid ItemId { get; set; }

    public Guid GroupId { get; set; }

    public int PermissionTypeId { get; set; }

    public bool? Allowed { get; set; }

    public bool? PrintAllowed { get; set; }

    public bool? WriteAllowed { get; set; }

    public bool? ExportAllowed { get; set; }

    public bool? DeleteAllowed { get; set; }

    public bool? InsertAllowed { get; set; }

    public bool? ImportAllowed { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Group Group { get; set; }
}