// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class PlayerDomain
{
    public Guid PlayerDomainId { get; set; }

    public Guid PlayerId { get; set; }

    public Guid DomainId { get; set; }

    public DateTimeOffset? Date { get; set; }

    public Guid? ClubId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? MemberId { get; set; }

    public string MemberCardId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Domain Domain { get; set; }

    public virtual Player Player { get; set; }
}