// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class PlayerAccount
{
    public Guid PlayerAccountId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? AccountTypeId { get; set; }

    public decimal? Balance { get; set; }

    public decimal? BalanceNotWithdrawable { get; set; }

    public decimal? CreditAmount { get; set; }

    public string Remarks { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Player Player { get; set; }
}