// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class PlayerViplevel
{
    public Guid VipcampaignId { get; set; }

    public Guid ViplevelId { get; set; }

    public Guid PlayerId { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? Expiration { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}