// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class PlayerClub
{
    public Guid PlayerClubId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? ClubId { get; set; }

    public string CardNumber { get; set; }

    public DateTime? CardExpiration { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Club Club { get; set; }

    public virtual Player Player { get; set; }
}