// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class RankingReward
{
    public Guid RankingRewardId { get; set; }

    public Guid? RankingId { get; set; }

    public long? Position { get; set; }

    public decimal? Value { get; set; }

    public string Description { get; set; }

    public byte[] Image { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Ranking Ranking { get; set; }
}