// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class RankingPlayer
{
    public Guid RankingPlayerId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? RankingId { get; set; }

    public long? Position { get; set; }

    public long? PreviousPosition { get; set; }

    public decimal? Points { get; set; }

    public decimal? PreviousPoints { get; set; }

    public long? EventCount { get; set; }

    public long? PreviousEventCount { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public int? InTheMoneyCount { get; set; }

    public int? FinalTableCount { get; set; }

    public int? WinsCount { get; set; }

    public decimal? TotalWinAmount { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Ranking Ranking { get; set; }
}