// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class RankingPlayerPoint
{
    public Guid RankingPlayerPointsId { get; set; }

    public Guid? RankingId { get; set; }

    public Guid? TournamentId { get; set; }

    public Guid? TournamentPlayerId { get; set; }

    public Guid? PlayerId { get; set; }

    public DateTime? Date { get; set; }

    public decimal? Points { get; set; }

    public string Description { get; set; }

    public string Error { get; set; }

    public int? EventCategoryId { get; set; }

    public Guid? LeagueId { get; set; }

    public bool? Itm { get; set; }

    public int? Entries { get; set; }

    public int? Position { get; set; }

    public bool? FinalTable { get; set; }

    public decimal? TotalPayoutAmount { get; set; }

    public decimal? AssignedPoints { get; set; }

    public decimal? ManualPoints { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Ranking Ranking { get; set; }
}