// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Ranking
{
    public Guid RankingId { get; set; }

    public Guid? SeasonId { get; set; }

    public string Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? EventCount { get; set; }

    public int? TotalEventCount { get; set; }

    public int? TotalPlayerCount { get; set; }

    public string Formula { get; set; }

    public int? Sex { get; set; }

    public int? EventType { get; set; }

    public int? WebPublishModality { get; set; }

    public DateTime? LastUpdated { get; set; }

    public bool? AutoCalculate { get; set; }

    public bool? Monthly { get; set; }

    public bool? Yearly { get; set; }

    public bool? AllTime { get; set; }

    public string CashFormula { get; set; }

    public int? TournamentType { get; set; }

    public Guid? ClubId { get; set; }

    public string Remarks { get; set; }

    public string Code { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<RankingLeague> RankingLeagues { get; set; } = new List<RankingLeague>();

    public virtual ICollection<RankingPlayerPoint> RankingPlayerPoints { get; set; } = new List<RankingPlayerPoint>();

    public virtual ICollection<RankingPlayer> RankingPlayers { get; set; } = new List<RankingPlayer>();

    public virtual ICollection<RankingReward> RankingRewards { get; set; } = new List<RankingReward>();

    public virtual ICollection<RankingTournament> RankingTournaments { get; set; } = new List<RankingTournament>();
}