// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class RankingTournament
{
    public Guid RankingTournamentId { get; set; }

    public Guid? RankingId { get; set; }

    public Guid? TournamentId { get; set; }

    public bool? Include { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Ranking Ranking { get; set; }
}