// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Release
{
    public Guid ReleaseId { get; set; }

    public int? Version { get; set; }

    public DateTime? UpdateDate { get; set; }
}