// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Report
{
    public Guid ReportId { get; set; }

    public string Image { get; set; }

    public string RecordSelectionFormula { get; set; }

    public string Classname { get; set; }

    public string Filter { get; set; }

    public virtual ICollection<ReportLink> ReportLinks { get; set; } = new List<ReportLink>();
}