// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class ReportLink
{
    public Guid ReportId { get; set; }

    public Guid LinkId { get; set; }

    public virtual Report Report { get; set; }
}