// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class SeasonLeagueFormula
{
    public Guid SeasonLeagueFormulaId { get; set; }

    public Guid SeasonLeagueId { get; set; }

    public int FromPosition { get; set; }

    public int ToPosition { get; set; }

    public string Formula { get; set; }
}