// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class SeasonLeague
{
    public Guid SeasonLeagueId { get; set; }

    public Guid SeasonId { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public Guid? CustomReportId { get; set; }

    public Guid? CashReportId { get; set; }

    public decimal? HouseContributionPercentage { get; set; }

    public bool? Reserved { get; set; }

    public string Formula { get; set; }

    public int? EventCount { get; set; }

    public bool? TeamEnabled { get; set; }

    public int? TeamMemberPerEvent { get; set; }

    public decimal? TeamClassifiedPercentage { get; set; }

    public Guid? PromotionId { get; set; }

    public double? HouseContributionValuePerEntry { get; set; }

    public byte[] LogoContent { get; set; }

    public string Note { get; set; }

    public bool? ExternalManaged { get; set; }

    public string Announcements { get; set; }

    public string Code { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? LastUpdated { get; set; }

    public bool? LiveHidden { get; set; }

    public bool? LiveShowAllNames { get; set; }

    public Guid? WaiverDocumentId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Season Season { get; set; }

    public virtual ICollection<SeasonLeagueStage> SeasonLeagueStages { get; set; } = new List<SeasonLeagueStage>();
}