// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Season
{
    public Guid SeasonId { get; set; }

    public string SeasonDescription { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public bool? Reserved { get; set; }

    public DateTime? LastUpdated { get; set; }

    public Guid? PromotionId { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<SeasonLeague> SeasonLeagues { get; set; } = new List<SeasonLeague>();
}