// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class SeasonLeagueStage
{
    public Guid SeasonLeagueStageId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public string SeasonLeagueStageDescription { get; set; }

    public int? StageIndex { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual SeasonLeague SeasonLeague { get; set; }
}