// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Server
{
    public Guid ServerId { get; set; }

    public string ServerName { get; set; }

    public string ServerDescription { get; set; }

    public string HardwareId { get; set; }

    public DateTime? LastAccess { get; set; }

    public string Code { get; set; }

    public string Version { get; set; }

    public long? VersionNumber { get; set; }

    public string VersionReleaseId { get; set; }

    public string VersionType { get; set; }

    public DateTime? InstallationDate { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<ServerAddon> ServerAddons { get; set; } = new List<ServerAddon>();

    public virtual ICollection<ServerBackup> ServerBackups { get; set; } = new List<ServerBackup>();
}