// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class ServerAddon
{
    public Guid ServerAddonId { get; set; }

    public string ServerAddonDescription { get; set; }

    public Guid? ServerId { get; set; }

    public string Version { get; set; }

    public int? VersionNumber { get; set; }

    public int? ApplicationMinimumVersion { get; set; }

    public DateTime? InstallationDate { get; set; }

    public bool? Enabled { get; set; }

    public string Name { get; set; }

    public byte[] Content { get; set; }

    public long? ContentLength { get; set; }

    public bool? ExternalService { get; set; }

    public bool? Reserved { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Server Server { get; set; }
}