// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class ServerBackup
{
    public Guid ServerBackupId { get; set; }

    public Guid? ServerId { get; set; }

    public int? Type { get; set; }

    public long? Ticks { get; set; }

    public string Location { get; set; }

    public int? Value { get; set; }

    public bool? Enabled { get; set; }

    public DateTime? ProcessDate { get; set; }

    public string BackupDescription { get; set; }

    public string StatusDescription { get; set; }

    public int? LocationType { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Server Server { get; set; }
}