// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class ServerAddonEntity
{
    public Guid ServerAddonEntityId { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public string Key { get; set; }

    public string Name { get; set; }

    public byte[] Content { get; set; }

    public long? ContentLength { get; set; }

    public DateTime? CreationDate { get; set; }

    public DateTime? LastUpdated { get; set; }
}