// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Session
{
    public Guid SessionId { get; set; }

    public Guid UserId { get; set; }

    public string Username { get; set; }

    public string Hostname { get; set; }

    public DateTime? SessionDate { get; set; }

    public DateTime? ExpireDate { get; set; }

    public string DeviceId { get; set; }

    public string DeviceName { get; set; }

    public string DeviceOs { get; set; }

    public string DeviceVersion { get; set; }

    public string DeviceUniqueId { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ClubId { get; set; }
}