// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Sm
{
    public Guid Smsid { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? ScheduleDate { get; set; }

    public string Sender { get; set; }

    public string Body { get; set; }

    public int? Messages { get; set; }

    public int? Quality { get; set; }

    public int? Result { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public string ReferenceDescription { get; set; }

    public double? TotalCredit { get; set; }

    public byte[] Timestamp { get; set; }

    public bool Deleted { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<Smsrecipient> Smsrecipients { get; set; } = new List<Smsrecipient>();
}