// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class SmsActivity
{
    public Guid SmsActivityId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public Guid? ReferenceItemId { get; set; }

    public string ReferenceDescription { get; set; }

    public string Number { get; set; }

    public string Text { get; set; }

    public int? Messages { get; set; }

    public string ProviderName { get; set; }

    public string ProviderIdentifier { get; set; }

    public string ProviderStatusCode { get; set; }

    public string ProviderStatusDescription { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}