// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Smsrecipient
{
    public Guid SmsrecipientId { get; set; }

    public Guid Smsid { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? Delivery { get; set; }

    public string Number { get; set; }

    public string Body { get; set; }

    public int? Messages { get; set; }

    public int? Quality { get; set; }

    public int? Result { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public string ReferenceDescription { get; set; }

    public double? TotalCredit { get; set; }

    public byte[] Timestamp { get; set; }

    public string ErrorMessage { get; set; }

    public string Identifier { get; set; }

    public string ErrorCode { get; set; }

    public string ProviderName { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Sm Sms { get; set; }
}