// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class SyncHistory
{
    public Guid Id { get; set; }

    public DateTime Date { get; set; }

    public int Type { get; set; }

    public Guid UpdId { get; set; }

    public DateTime UpdDate { get; set; }

    public int UpdVersion { get; set; }
}