// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class SyncRow
{
    public Guid Id { get; set; }

    public string Tablename { get; set; }

    public int? Type { get; set; }

    public string Keys { get; set; }

    public DateTime? Date { get; set; }

    public int? Status { get; set; }
}