// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class SyncStatus
{
    public int Type { get; set; }

    public DateTime? Date { get; set; }

    public long? Length { get; set; }

    public string Error { get; set; }

    public DateTime? Lastupdate { get; set; }
}