// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class SyncTable
{
    public string Name { get; set; }

    public int Version { get; set; }

    public DateTime Installedon { get; set; }

    public byte[] Uninstall { get; set; }
}