// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TeamMember
{
    public Guid TeamMemberId { get; set; }

    public Guid? TeamId { get; set; }

    public Guid? PlayerId { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string Note { get; set; }

    public bool? Reserve { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Team Team { get; set; }
}