// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TemplatePayoutStruct
{
    public Guid TemplatePayoutStructId { get; set; }

    public Guid? TemplatePayoutId { get; set; }

    public int? PayoutTypeId { get; set; }

    public int? PlayerCountMin { get; set; }

    public int? PlayerCountMax { get; set; }

    public int? PayoutCount { get; set; }

    public double? RoundValue { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual TemplatePayout TemplatePayout { get; set; }

    public virtual ICollection<TemplatePayoutRate> TemplatePayoutRates { get; set; } = new List<TemplatePayoutRate>();
}