// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TemplatePayoutRate
{
    public Guid TemplatePayoutRateId { get; set; }

    public Guid? TemplatePayoutStructId { get; set; }

    public int? StartPosition { get; set; }

    public int? EndPosition { get; set; }

    public double? Value { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual TemplatePayoutStruct TemplatePayoutStruct { get; set; }
}