// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TemplateLevelStruct
{
    public Guid TemplateLevelStructId { get; set; }

    public Guid? TemplateLevelId { get; set; }

    public int? LevelIndex { get; set; }

    public int? LevelType { get; set; }

    public double? Ante { get; set; }

    public double? SmallBlind { get; set; }

    public double? BigBlind { get; set; }

    public double? Duration { get; set; }

    public Guid? GameTypeId { get; set; }

    public bool ChipRaise { get; set; }

    public int? OrderIndex { get; set; }

    public double? Limit1 { get; set; }

    public double? Limit2 { get; set; }

    public string Note { get; set; }

    public double? BringIn { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual TemplateLevel TemplateLevel { get; set; }
}