// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TemplatePayout
{
    public Guid TemplatePayoutId { get; set; }

    public string TemplatePayoutDescription { get; set; }

    public DateTime? LastUpdate { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<TemplatePayoutStruct> TemplatePayoutStructs { get; set; } = new List<TemplatePayoutStruct>();
}