// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Ticket
{
    public Guid TicketId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? UserId { get; set; }

    public Guid? TransactionTypeId { get; set; }

    public Guid TicketTypeId { get; set; }

    public Guid? TicketItemId { get; set; }

    public string Description { get; set; }

    public bool WithdrawAllowed { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? Expiration { get; set; }

    public decimal? Value { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ReferenceItemId { get; set; }

    public Guid? TransactionId { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? CreationDate { get; set; }

    public Guid? CreationUserId { get; set; }

    public bool? Withdrawed { get; set; }

    public int? DeductionTypeId { get; set; }

    public Guid? TicketItemChildId { get; set; }

    public Guid? DomainTicketId { get; set; }

    public Guid? CurrencyId { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}