// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentAudioItem
{
    public Guid TournamentAudioItemId { get; set; }

    public Guid TournamentAudioId { get; set; }

    public int EventName { get; set; }

    public int AudioType { get; set; }

    public byte[] Content { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual TournamentAudio TournamentAudio { get; set; }
}