// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentTheme
{
    public Guid TournamentThemeId { get; set; }

    public string Description { get; set; }

    public int? Color { get; set; }

    public int? ColorContrast { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<TournamentThemeAspect> TournamentThemeAspects { get; set; } = new List<TournamentThemeAspect>();
}