// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentPlayer
{
    public Guid TournamentPlayerId { get; set; }

    public Guid TournamentId { get; set; }

    public Guid? PlayerId { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public int? Status { get; set; }

    public bool Addon { get; set; }

    public int? RebuyCount { get; set; }

    public double? KnockOutCount { get; set; }

    public Guid? KnockedOutPlayerId { get; set; }

    public Guid? TournamentTableId { get; set; }

    public int? TournamentTableSitIndex { get; set; }

    public int? Ticket { get; set; }

    public DateTimeOffset? SubscriptionDate { get; set; }

    public DateTimeOffset? EliminationDate { get; set; }

    public int? Position { get; set; }

    public bool Payed { get; set; }

    public double? PayedCash { get; set; }

    public double? PayedCheck { get; set; }

    public double? PayedChips { get; set; }

    public double? PayedSatellite { get; set; }

    public double? PayedBonus { get; set; }

    public double? PayoutAmount { get; set; }

    public string CheckinAnnotation { get; set; }

    public double? Points { get; set; }

    public double? ChipsCount { get; set; }

    public Guid? EliminationLevelId { get; set; }

    public int? EliminationLevelIndex { get; set; }

    public double? LeaguePoints { get; set; }

    public int? Trend { get; set; }

    public bool? Itm { get; set; }

    public int? EliminationTableIndex { get; set; }

    public int? EliminationTableSitIndex { get; set; }

    public Guid? ReferenceId { get; set; }

    public bool? SpecialEvent { get; set; }

    public int? TournamentTableIndex { get; set; }

    public Guid? CurrencyId { get; set; }

    public bool? ReEntry { get; set; }

    public Guid? NetworkUniqueId { get; set; }

    public Guid? SponsorId { get; set; }

    public int? EliminationPosition { get; set; }

    public long? EliminationLevelSeconds { get; set; }

    public int? EliminationDay { get; set; }

    public string EliminationGroup { get; set; }

    public string AuthorizationId { get; set; }

    public bool? PayoutAssigned { get; set; }

    public DateTimeOffset? PayoutDate { get; set; }

    public decimal? PayoutKnockOutAmount { get; set; }

    public bool? Punctuality { get; set; }

    public double? KnockOutAmount { get; set; }

    public double? KnockOutValue { get; set; }

    public string SubscriptionTransactionId { get; set; }

    public bool? Qualified { get; set; }

    public string SatelliteAuthorizationId { get; set; }

    public decimal? SubscriptionTotalDue { get; set; }

    public Guid? SubscriptionUserId { get; set; }

    public Guid? EliminationUserId { get; set; }

    public string Note { get; set; }

    public Guid? TeamId { get; set; }

    public int? AddonCount { get; set; }

    public Guid? PayoutTicketId { get; set; }

    public decimal? HouseAmount { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? Buyin { get; set; }

    public decimal? Fee { get; set; }

    public decimal? RebuyHouseAmount { get; set; }

    public decimal? AddonHouseAmount { get; set; }

    public decimal? RebuyTaxAmount { get; set; }

    public decimal? AddonTaxAmount { get; set; }

    public int? Entries { get; set; }

    public decimal? SubscriptionPaidAmount { get; set; }

    public decimal? RebuyPaidAmount { get; set; }

    public decimal? AddonPaidAmount { get; set; }

    public Guid? PayoutUserId { get; set; }

    public int? SubscriptionLevelIndex { get; set; }

    public Guid? IncomingTournamentId { get; set; }

    public Guid? SubscriptionTournamentChildId { get; set; }

    public string SubscriptionDayDescription { get; set; }

    public Guid? NetworkEventSourceId { get; set; }

    public Guid? TournamentBuyinId { get; set; }

    public int? Entry { get; set; }

    public int? SubscriptionDay { get; set; }

    public string SubscriptionGroup { get; set; }

    public int? EntryDay { get; set; }

    public string SubscriptionPaymentDescription { get; set; }

    public decimal? RebuyAmount { get; set; }

    public decimal? RebuyFeeAmount { get; set; }

    public decimal? AddonAmount { get; set; }

    public decimal? AddonFeeAmount { get; set; }

    public decimal? DoubleChanceAmount { get; set; }

    public decimal? DoubleChanceFeeAmount { get; set; }

    public decimal? DoubleChanceHouseAmount { get; set; }

    public decimal? DoubleChanceTaxAmount { get; set; }

    public int? DoubleChanceCount { get; set; }

    public decimal? DoubleChancePaidAmount { get; set; }

    public decimal? TotalDue { get; set; }

    public decimal? TotalProfit { get; set; }

    public Guid? PlayerCardTypeId { get; set; }

    public decimal? PayoutAssignedAmount { get; set; }

    public decimal? PayoutAssignedSpp { get; set; }

    public int? PayoutAssignedTicketCount { get; set; }

    public decimal? TicketBonusAmount { get; set; }

    public decimal? PayoutAssignedTicketAmount { get; set; }

    public int? TicketBonusCount { get; set; }

    public string ClubCardNumber { get; set; }

    public long? WaitingTicket { get; set; }

    public DateTime? LastUpdated { get; set; }

    public DateTimeOffset? CheckInDate { get; set; }

    public DateTimeOffset? ChipsCountLastUpdated { get; set; }

    public DateTimeOffset? WaitingSubscriptionDate { get; set; }

    public int? EliminationReason { get; set; }

    public long? EliminationChipsCount { get; set; }

    public Guid? DomainTicketId { get; set; }

    public string KnockedOutPlayersIdstring { get; set; }

    public int? TimebankCount { get; set; }

    public int? EliminationTimebankCount { get; set; }

    public int? LastTimeBankCount { get; set; }

    public decimal? PayoutAmountOriginal { get; set; }

    public bool? PayoutDeal { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}