// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentUser
{
    public Guid TournamentId { get; set; }

    public Guid UserId { get; set; }

    public bool Payed { get; set; }

    public double? PayAmount { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }

    public virtual User User { get; set; }
}