// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentBuyin
{
    public Guid TournamentBuyinId { get; set; }

    public Guid TournamentId { get; set; }

    public decimal? Buyin { get; set; }

    public decimal? Fee { get; set; }

    public decimal? Chips { get; set; }

    public int? LevelIndexBeginCondition { get; set; }

    public int? LevelIndexEndCondition { get; set; }

    public int? EntryBeginCondition { get; set; }

    public int? EntryEndCondition { get; set; }

    public int? DayCondition { get; set; }

    public string FlightCondition { get; set; }

    public decimal? ChipsForPunctuality { get; set; }

    public decimal? Spp { get; set; }

    public bool? Default { get; set; }

    public Guid? ReferenceId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}