// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentAudio
{
    public Guid TournamentAudioId { get; set; }

    public string TournamentAudioDescription { get; set; }

    public Guid? StoreId { get; set; }

    public bool? Reserved { get; set; }

    public int? UpdateVersion { get; set; }

    public Guid? ClubId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<TournamentAudioItem> TournamentAudioItems { get; set; } = new List<TournamentAudioItem>();
}