// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentLockedTableSeat
{
    public Guid TournamentLockedTableSeatId { get; set; }

    public int? TournamentTableSeatIndex { get; set; }

    public Guid? TournamentTableId { get; set; }

    public Guid? TournamentPlayerId { get; set; }

    public Guid TournamentId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}