// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentWaiting
{
    public Guid TournamentWaitingId { get; set; }

    public Guid? TournamentId { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public Guid? PlayerId { get; set; }

    public DateTimeOffset? SubscriptionDate { get; set; }

    public Guid? SubscriptionUserId { get; set; }

    public long? Ticket { get; set; }

    public string Note { get; set; }

    public decimal? SubscriptionPaidAmount { get; set; }

    public Guid? TournamentBuyinId { get; set; }

    public DateTimeOffset? LastNotification { get; set; }

    public string Nickname { get; set; }

    public DateTime? BirthDate { get; set; }

    public Guid? CountryId { get; set; }

    public string LiPokerCardId { get; set; }

    public string Number { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public long? PlayerTicket { get; set; }

    public string SubscriptionPaymentDescription { get; set; }

    public Guid? DomainTicketId { get; set; }

    public Guid? DomainId { get; set; }

    public Guid? ReservationId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}