// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentPenality
{
    public Guid TournamentPenalityId { get; set; }

    public Guid? TournamentId { get; set; }

    public Guid? TournamentPlayerId { get; set; }

    public double? Duration { get; set; }

    public double? Elapsed { get; set; }

    public string Note { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}