// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentChild
{
    public Guid TournamentChildId { get; set; }

    public Guid? TournamentId { get; set; }

    public DateTime? StartDate { get; set; }

    public int? StartLevelIndex { get; set; }

    public int? EndLevelIndex { get; set; }

    public int? PlayerAllowed { get; set; }

    public int? Day { get; set; }

    public string Group { get; set; }

    public decimal? Buyin { get; set; }

    public decimal? Fee { get; set; }

    public int? LevelMinutes { get; set; }

    public string CustomDescription { get; set; }

    public int? MaxEntriesPerPlayer { get; set; }

    public decimal? SubscriptionSpp { get; set; }

    public string QualificationGroup { get; set; }

    public string DayGroupDescription { get; set; }

    public bool? LevelStructureLocked { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}