// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentRateExpanded
{
    public Guid TournamentRateExpandedId { get; set; }

    public int? Position { get; set; }

    public double? RateValue { get; set; }

    public Guid TournamentId { get; set; }

    public Guid TournamentRateId { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}