// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentRate
{
    public Guid TournamentRateId { get; set; }

    public Guid TournamentId { get; set; }

    public int? StartPosition { get; set; }

    public int? EndPosition { get; set; }

    public decimal? RateValue { get; set; }

    public decimal? Spp { get; set; }

    public string CustomDescription { get; set; }

    public decimal? OriginalValue { get; set; }

    public bool? Deal { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}