// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentWebDetail
{
    public Guid TournamentId { get; set; }

    public byte[] Logo { get; set; }

    public byte[] Banner { get; set; }

    public DateTime? LastUpload { get; set; }

    public string Note { get; set; }

    public bool? ReadyForUpload { get; set; }

    public bool? Visible { get; set; }

    public string BuyinDescription { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}