// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentReservation
{
    public Guid TournamentReservationId { get; set; }

    public Guid? TournamentId { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string Nickname { get; set; }

    public DateTime? BirthDate { get; set; }

    public Guid? CountryId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? SubscriptionUserId { get; set; }

    public DateTimeOffset? SubscriptionDate { get; set; }

    public Guid? BuyinId { get; set; }

    public string Note { get; set; }

    public int? TableIndex { get; set; }

    public int? TableSeatIndex { get; set; }

    public string Identifier { get; set; }

    public string Email { get; set; }

    public Guid? PaymentModalityId { get; set; }

    public string Number { get; set; }

    public Guid? ReferenceId { get; set; }

    public string Source { get; set; }

    public string Account { get; set; }

    public string LiPokerCardId { get; set; }

    public string PhoneNumber { get; set; }

    public int? Flags { get; set; }

    public bool? IsSelfRegistrationAllowed { get; set; }

    public Guid? DomainTicketId { get; set; }

    public Guid? DomainId { get; set; }

    public string ExternalSource { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}