// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentAction
{
    public Guid TournamentActionId { get; set; }

    public Guid TournamentId { get; set; }

    public Guid? TournamentPlayerId { get; set; }

    public string TournamentPlayerLastname { get; set; }

    public string TournamentPlayerFirstname { get; set; }

    public Guid? PreviousTableId { get; set; }

    public int PreviousTableIndex { get; set; }

    public int PreviousTableSeatIndex { get; set; }

    public Guid? PreviousLevelId { get; set; }

    public int PreviousLevelIndex { get; set; }

    public double PreviousLevelDuration { get; set; }

    public double PreviousLevelElapsedTime { get; set; }

    public Guid? CurrentTableId { get; set; }

    public int CurrentTableIndex { get; set; }

    public int CurrentTableSeatIndex { get; set; }

    public Guid? CurrentLevelId { get; set; }

    public int CurrentLevelIndex { get; set; }

    public double CurrentLevelDuration { get; set; }

    public double CurrentLevelElapsedTime { get; set; }

    public int ActionType { get; set; }

    public DateTimeOffset ActionDateTime { get; set; }

    public Guid UserId { get; set; }

    public string UserLastname { get; set; }

    public string UserFirstname { get; set; }

    public string UserUsername { get; set; }

    public string CurrentGroup { get; set; }

    public string PreviousGroup { get; set; }

    public Guid? PlayerId { get; set; }

    public long? Ticket { get; set; }

    public Guid? TicketId { get; set; }

    public string TicketDescription { get; set; }

    public decimal? TicketValue { get; set; }

    public string ExtraData { get; set; }

    public int? CurrentDay { get; set; }

    public Guid? ReferenceId { get; set; }

    public string Remarks { get; set; }

    public Guid? BuyinId { get; set; }

    public int? EliminationPosition { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}