// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentLevel
{
    public Guid TournamentLevelId { get; set; }

    public int? LevelIndex { get; set; }

    public int? LevelType { get; set; }

    public double? Ante { get; set; }

    public double? SmallBlind { get; set; }

    public double? BigBlind { get; set; }

    public double? Duration { get; set; }

    public Guid? GameTypeId { get; set; }

    public bool ChipRaise { get; set; }

    public Guid TournamentId { get; set; }

    public int? OrderIndex { get; set; }

    public int? StopEvent { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? ExpectedTime { get; set; }

    public double? Limit1 { get; set; }

    public double? Limit2 { get; set; }

    public string Note { get; set; }

    public double? BringIn { get; set; }

    public int? TimeBankCount { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}