// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentTable
{
    public Guid TournamentTableId { get; set; }

    public Guid TournamentId { get; set; }

    public Guid? DealerId { get; set; }

    public int? TableIndex { get; set; }

    public int? Status { get; set; }

    public int? SitCount { get; set; }

    public int? CloseOrderIndex { get; set; }

    public string Note { get; set; }

    public Guid? ClubRoomId { get; set; }

    public byte[] SeatsData { get; set; }

    public DateTimeOffset? ChipsCountLastUpdated { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Tournament Tournament { get; set; }
}