// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TournamentBillboard
{
    public Guid TournamentBillboardId { get; set; }

    public string TournamentBillboardDescription { get; set; }

    public DateTime? BeginDate { get; set; }

    public DateTime? EndDate { get; set; }

    public Guid? SeasonId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public Guid? ClubId { get; set; }

    public bool? ShowOnlySubscriptionOpened { get; set; }

    public bool? IncludeCompleted { get; set; }

    public DateTime? SyncLastupdated { get; set; }
}