// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class UserPerClub
{
    public Guid UserId { get; set; }

    public Guid ClubId { get; set; }

    public bool? Allowed { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Club Club { get; set; }

    public virtual User User { get; set; }
}