// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VAppSetting
{
    public Guid Id { get; set; }

    public Guid AppSettingsId { get; set; }

    public string WebUsername { get; set; }

    public string WebProtectedPassword { get; set; }

    public string Smssender { get; set; }
}