// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VArticle
{
    public Guid Id { get; set; }

    public Guid ArticleId { get; set; }

    public string ArticleDescription { get; set; }

    public Guid? ArticleFamilyId { get; set; }

    public string Code { get; set; }

    public double? TaxRate { get; set; }

    public string MeasureUnit { get; set; }

    public double? PreviousCost { get; set; }

    public double? LastCost { get; set; }

    public double? AverageCost { get; set; }

    public double? AveragePrice { get; set; }

    public bool Cancelled { get; set; }

    public string Ean { get; set; }

    public double? Price { get; set; }

    public byte[] Image { get; set; }

    public double? PurchasedQuantity { get; set; }

    public double? SelledQuantity { get; set; }

    public double? Quantity { get; set; }

    public string SearchText { get; set; }

    public string ArticleFamilyDescription { get; set; }

    public string Path { get; set; }

    public Guid ClubId { get; set; }

    public string ClubDescription { get; set; }
}