// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VArticleStock
{
    public Guid Id { get; set; }

    public Guid ArticleStockId { get; set; }

    public Guid? ArticleId { get; set; }

    public double? PurchasedQuantity { get; set; }

    public double? SelledQuantity { get; set; }

    public double? Quantity { get; set; }
}