// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VAttachment
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public Guid AttachmentId { get; set; }

    public Guid AttachmentTypeId { get; set; }

    public Guid? PlayerId { get; set; }

    public DateTime Date { get; set; }

    public string Extension { get; set; }

    public string Note { get; set; }

    public byte[] Content { get; set; }

    public byte[] Preview { get; set; }

    public Guid? UserId { get; set; }

    public long? Length { get; set; }

    public DateTime? LastUpdated { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public Guid? ReferenceItemId { get; set; }

    public Guid? ReferenceParentId { get; set; }

    public string ReferenceDescription { get; set; }

    public bool? Reserved { get; set; }

    public bool? Hidden { get; set; }

    public string AttachmentTypeDescription { get; set; }

    public Guid? ClubId { get; set; }

    public DateTimeOffset? Expiration { get; set; }

    public Guid? StorageProviderId { get; set; }

    public bool? Expired { get; set; }

    public string PlayerDescription { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string CountryCode { get; set; }

    public string CountryDescription { get; set; }

    public DateTime? BirthDate { get; set; }

    public string Username { get; set; }

    public string UserDescription { get; set; }
}