// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VBlackListPlayer
{
    public Guid Id { get; set; }

    public string SearchText { get; set; }

    public Guid BlackListPlayerId { get; set; }

    public string Account { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public DateTime? BirthDate { get; set; }

    public string Email { get; set; }

    public Guid BlackListId { get; set; }

    public string BlackListDescription { get; set; }

    public bool? EnableForTournament { get; set; }

    public bool? EnableForPlayer { get; set; }

    public bool? EnableForCash { get; set; }

    public string CustomErrorMessage { get; set; }

    public string NormalizedLastname { get; set; }

    public string NormalizedFirstname { get; set; }
}