// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VBlackList
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid BlackListId { get; set; }

    public string BlackListDescription { get; set; }

    public bool? EnableForTournament { get; set; }

    public bool? EnableForPlayer { get; set; }

    public bool? EnableForCash { get; set; }

    public string CustomErrorMessage { get; set; }
}