// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VCashPlayerDetail
{
    public int? Year { get; set; }

    public int? Month { get; set; }

    public int? Day { get; set; }

    public Guid CashPlayerId { get; set; }

    public DateTime? SubscriptionDate { get; set; }

    public DateTime? CheckinDate { get; set; }

    public DateTime? CheckoutDate { get; set; }

    public int? Status { get; set; }

    public int? InactivityTicks { get; set; }

    public double? TotalMinutesPlayed { get; set; }

    public Guid PlayerId { get; set; }

    public string PlayerFullname { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public Guid? CountryId { get; set; }

    public string CardNumber { get; set; }

    public Guid CashSessionId { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? BeginDate { get; set; }

    public DateTime? EndDate { get; set; }

    public Guid CashTypeId { get; set; }

    public double? SmallBlind { get; set; }

    public double? BigBlind { get; set; }

    public int? SitCount { get; set; }

    public Guid? SeasonId { get; set; }

    public string SeasonDescription { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public string CountryDescription { get; set; }

    public byte[] Flag { get; set; }
}