// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VCashPlayersCalculationDatum
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public DateTime? BeginDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? TotalPlayers { get; set; }

    public double? TotalRake { get; set; }

    public int? UniquePlayersCount { get; set; }

    public int EventTypeId { get; set; }

    public DateTimeOffset? Date { get; set; }

    public Guid? SeasonId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public Guid ReferenceId { get; set; }

    public string ReferenceDescription { get; set; }

    public string ReferenceTypeId { get; set; }

    public Guid CashPlayerId { get; set; }

    public DateTimeOffset? CheckinDate { get; set; }

    public DateTimeOffset? CheckoutDate { get; set; }

    public DateTimeOffset? SubscriptionDate { get; set; }

    public int? Status { get; set; }

    public double? TotalMinutesPlayed { get; set; }

    public long? InactivityTicks { get; set; }

    public long? Ticket { get; set; }

    public Guid ItemId { get; set; }

    public Guid? CashTypeId { get; set; }

    public Guid ReferenceItemId { get; set; }

    public DateTimeOffset? ReferenceDate { get; set; }

    public decimal? StackTotalAmount { get; set; }

    public decimal? CashOutTotalAmount { get; set; }

    public decimal? TipTotalAmount { get; set; }

    public DateTimeOffset? ShowUpDate { get; set; }

    public decimal? ProfitTotalAmount { get; set; }

    public double? BigBlind { get; set; }

    public double? SmallBlind { get; set; }

    public int? SitCount { get; set; }

    public string CurrencySymbol { get; set; }

    public string CurrencyDescription { get; set; }

    public string GameTypeCode { get; set; }

    public string GameTypeDescription { get; set; }

    public Guid PlayerId { get; set; }

    public int? Sex { get; set; }

    public string MembershipCardTypeCode { get; set; }

    public string MembershipCardTypeDescription { get; set; }

    public string SeasonDescription { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public Guid? PromotionId { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public string ClubCode { get; set; }
}