// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VCashSession
{
    public Guid Id { get; set; }

    public string SearchText { get; set; }

    public Guid CashSessionId { get; set; }

    public int? Code { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? BeginDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? LastTicketNumber { get; set; }

    public int? Status { get; set; }

    public Guid? SeasonId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public double? TotalRake { get; set; }

    public double? TotalMinutesPlayed { get; set; }

    public int? TotalPlayers { get; set; }

    public Guid? PromotionId { get; set; }

    public string SeasonDescription { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public DateTime? LastUpdated { get; set; }

    public Guid ClubId { get; set; }

    public string ClubDescription { get; set; }

    public Guid? ServerId { get; set; }

    public string ServerName { get; set; }

    public string ServerDescription { get; set; }

    public string HardwareId { get; set; }
}