// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VCashPlayerPointsPerCashType
{
    public Guid? PlayedCashTypeId { get; set; }

    public Guid CashSessionId { get; set; }

    public double? Vippoints { get; set; }

    public double? TotalMinutesPlayed { get; set; }
}