// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VCashTable
{
    public Guid CashTableId { get; set; }

    public DateTime? ActivateDate { get; set; }

    public DateTime? OpenDate { get; set; }

    public DateTime? CloseDate { get; set; }

    public int? Index { get; set; }

    public int? Status { get; set; }

    public int? TotalEntries { get; set; }

    public int? TotalHands { get; set; }

    public decimal? TotalRakePerHandAmount { get; set; }

    public decimal? TotalPotPerHandAmount { get; set; }

    public decimal? TotalStackAmount { get; set; }

    public double? Rake { get; set; }

    public Guid? ClubId { get; set; }

    public Guid CashTypeId { get; set; }

    public string Description { get; set; }

    public string ShortDescription { get; set; }

    public double? SmallBlind { get; set; }

    public double? BigBlind { get; set; }

    public double? Ante { get; set; }

    public double? Straddle { get; set; }

    public double? BringIn { get; set; }

    public int? Color { get; set; }

    public decimal? MinBuyin { get; set; }

    public decimal? MaxBuyin { get; set; }

    public bool? AllowHandRecording { get; set; }

    public bool? AllowNoRake { get; set; }

    public decimal? RakeValue { get; set; }

    public int? RakeValueType { get; set; }

    public decimal? RakeAmountCap { get; set; }

    public decimal? RakeTimedAmount { get; set; }

    public int? RakeTimedMinutes { get; set; }

    public int? RakeType { get; set; }

    public Guid GameTypeId { get; set; }

    public string GameTypeDescription { get; set; }

    public Guid? SeasonId { get; set; }

    public string SeasonDescription { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public string SeasonLeagueDescription { get; set; }
}