// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VCashSessionTransaction
{
    public string PlayerDescription { get; set; }

    public string PaymentModalityDescription { get; set; }

    public int? PaymentTypeId { get; set; }

    public bool? SystemPaymentModality { get; set; }

    public DateTime Date { get; set; }

    public decimal? AccountValue { get; set; }

    public Guid? AccountTypeId { get; set; }

    public decimal? Value { get; set; }

    public decimal? Sppvalue { get; set; }

    public decimal? Vipvalue { get; set; }

    public Guid TransactionTypeId { get; set; }

    public Guid PlayerId { get; set; }

    public Guid? PaymentModalityId { get; set; }

    public Guid TransactionId { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ReferenceItemId { get; set; }

    public string ReferenceDescription { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public Guid? TicketId { get; set; }

    public Guid? CashSessionId { get; set; }

    public Guid? ClubId { get; set; }

    public Guid? UserId { get; set; }

    public string Username { get; set; }

    public string UserDescription { get; set; }
}