// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VCountry
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid CountryId { get; set; }

    public string CountryDescription { get; set; }

    public byte[] Flag { get; set; }

    public byte[] Flag16 { get; set; }

    public string Nationality { get; set; }

    public string Code { get; set; }

    public string CodeExt { get; set; }

    public string Number { get; set; }

    public byte[] BinaryFlag { get; set; }
}