// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VCurrency
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid CurrencyId { get; set; }

    public string CurrencyDescription { get; set; }

    public string Symbol { get; set; }

    public string Code { get; set; }

    public string CurrencyName { get; set; }
}