// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VCustomReport
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid CustomReportId { get; set; }

    public string CustomReportDescription { get; set; }

    public Guid? ParentId { get; set; }

    public string Content { get; set; }

    public bool Reserved { get; set; }

    public byte[] Report { get; set; }

    public string Modules { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}