// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VDevice
{
    public Guid Id { get; set; }

    public string SearchText { get; set; }

    public Guid DeviceId { get; set; }

    public string Description { get; set; }

    public string Types { get; set; }

    public string Name { get; set; }

    public DateTime? CreationTime { get; set; }

    public DateTime? LastAccessTime { get; set; }

    public string Osversion { get; set; }

    public string UniqueId { get; set; }

    public string Version { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public Guid? ServerId { get; set; }

    public string ServerName { get; set; }

    public string ServerDescription { get; set; }

    public string HardwareId { get; set; }
}