// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VDocumentActivity
{
    public Guid Id { get; set; }

    public Guid DocumentActivityId { get; set; }

    public DateTime? DocumentActivityDate { get; set; }

    public Guid? CausalId { get; set; }

    public Guid? DocumentId { get; set; }

    public Guid? VendorId { get; set; }

    public Guid? ArticleId { get; set; }

    public string ArticleCode { get; set; }

    public string ArticleDescription { get; set; }

    public double? Quantity { get; set; }
}