// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VDocument
{
    public Guid Id { get; set; }

    public Guid DocumentId { get; set; }

    public DateTime? DocumentDate { get; set; }

    public Guid? DocumentTypeId { get; set; }

    public int? DocumentNumber { get; set; }

    public Guid? CustomerId { get; set; }

    public string CustomerLastname { get; set; }

    public string CustomerFirstname { get; set; }

    public Guid? VendorId { get; set; }

    public string VendorLastname { get; set; }

    public string VendorFirstname { get; set; }

    public double? Amount { get; set; }

    public double? PayedAmount { get; set; }

    public double? BonusAmount { get; set; }

    public double? CheckAmount { get; set; }

    public double? CreditCardAmount { get; set; }

    public double? CashAmount { get; set; }

    public double? ChipsAmount { get; set; }

    public string CustomerFullname { get; set; }

    public string VendorFullname { get; set; }

    public string SearchText { get; set; }

    public Guid ClubId { get; set; }

    public string ClubDescription { get; set; }
}