// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VDocumentTemplate
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public string DocumentTemplateDescription { get; set; }

    public byte[] ExtraData { get; set; }

    public int? ExpirationDays { get; set; }

    public byte[] Content { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public Guid? ServerId { get; set; }

    public string ServerName { get; set; }

    public string ServerDescription { get; set; }

    public string HardwareId { get; set; }
}