// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VDomain
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid DomainId { get; set; }

    public string DomainDescription { get; set; }

    public bool? AllowUpdateMembershipProfile { get; set; }
}