// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VDomainPlayerTicket
{
    public Guid Id { get; set; }

    public string SearchText { get; set; }

    public Guid DomainPlayerTicketId { get; set; }

    public string Description { get; set; }

    public DateTime? Date { get; set; }

    public int? Status { get; set; }

    public Guid? TypeId { get; set; }

    public bool? IsSelfRegistrationAllowed { get; set; }

    public string UniqueId { get; set; }

    public Guid? ReferenceId { get; set; }

    public byte[] ExtraData { get; set; }

    public byte[] OptionsData { get; set; }

    public string Note { get; set; }

    public DateTime? ProcessDate { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? ReferenceItemId { get; set; }

    public string StatusDescription { get; set; }

    public Guid? DomainId { get; set; }

    public Guid? DomainMemberId { get; set; }

    public bool? Processed { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public Guid? ServerId { get; set; }

    public string ServerName { get; set; }

    public string ServerDescription { get; set; }

    public string HardwareId { get; set; }
}