// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VDomainPlayerTicketDomainExport
{
    public Guid? ServerId { get; set; }

    public Guid? EntityId { get; set; }

    public Guid ReferenceId { get; set; }

    public Guid? Id { get; set; }

    public Guid? PlayerId { get; set; }
}