// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VFilter
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public Guid FilterId { get; set; }

    public string FilterDescription { get; set; }

    public Guid? EntityId { get; set; }

    public Guid? EntityLinkedId { get; set; }

    public string ParameterName { get; set; }

    public string ParameterReference { get; set; }

    public string Where { get; set; }

    public int? CategoryId { get; set; }

    public string SearchText { get; set; }
}