// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VGameType
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid GameTypeId { get; set; }

    public string GameTypeDescription { get; set; }

    public int? LimitTypeId { get; set; }

    public string Name { get; set; }

    public int? CategoryId { get; set; }
}