// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VGroup
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid GroupId { get; set; }

    public string GroupDescription { get; set; }

    public bool System { get; set; }

    public bool Reserved { get; set; }
}