// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class ViewColumn
{
    public Guid ColumnId { get; set; }

    public string Language { get; set; }

    public string ColumnName { get; set; }

    public string ColumnDescription { get; set; }

    public string FormatValue { get; set; }

    public int? Width { get; set; }

    public bool Visible { get; set; }

    public int? OrderIndex { get; set; }

    public Guid? ViewId { get; set; }

    public int? Type { get; set; }

    public string ClassType { get; set; }

    public bool? FixedWidth { get; set; }

    public string Modules { get; set; }

    public string Permissions { get; set; }

    public virtual View View { get; set; }
}