// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class View
{
    public Guid ViewId { get; set; }

    public string ViewName { get; set; }

    public string ViewDescription { get; set; }

    public string Query { get; set; }

    public string Join { get; set; }

    public string Where { get; set; }

    public string Group { get; set; }

    public string Order { get; set; }

    public string ClassType { get; set; }

    public virtual ICollection<ViewColumn> ViewColumns { get; set; } = new List<ViewColumn>();
}