// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Vipcampaign
{
    public Guid VipcampaignId { get; set; }

    public string Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public Guid? DefaultPromotionId { get; set; }

    public decimal? SppconversionMultiplier { get; set; }

    public decimal? VipconversionMultiplier { get; set; }

    public Guid? ClubId { get; set; }

    public string Note { get; set; }

    public string Url { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual ICollection<PlayerVip> PlayerVips { get; set; } = new List<PlayerVip>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual ICollection<Viplevel> Viplevels { get; set; } = new List<Viplevel>();

    public virtual ICollection<Vipproduct> Vipproducts { get; set; } = new List<Vipproduct>();
}