// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Viplevel
{
    public Guid ViplevelId { get; set; }

    public Guid VipcampaignId { get; set; }

    public decimal? PointsMultiplier { get; set; }

    public decimal? PointsToGain { get; set; }

    public decimal? PointsPerMonth { get; set; }

    public int? Level { get; set; }

    public string Description { get; set; }

    public Guid? DeclassingLevelId { get; set; }

    public int? PeriodTypeId { get; set; }

    public int? Color { get; set; }

    public int? ConversionLevel { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Vipcampaign Vipcampaign { get; set; }
}