// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VippromotionPerCashType
{
    public Guid VippromotionPerCashTypeId { get; set; }

    public Guid? VippromotionId { get; set; }

    public Guid? CashTypeId { get; set; }

    public decimal? PointsPerMinute { get; set; }

    public DateTime? SyncLastupdated { get; set; }

    public virtual Vippromotion Vippromotion { get; set; }
}