// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VLeague
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid SeasonLeagueId { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public Guid? CustomReportId { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public Guid SeasonId { get; set; }

    public bool? LiveShowAllNames { get; set; }

    public Guid? CashReportId { get; set; }

    public decimal? HouseContributionPercentage { get; set; }

    public double? HouseContributionValuePerEntry { get; set; }

    public string Code { get; set; }

    public bool? ExternalManaged { get; set; }

    public string Note { get; set; }

    public bool? Reserved { get; set; }

    public Guid? PromotionId { get; set; }

    public byte[] LogoContent { get; set; }

    public decimal? TeamClassifiedPercentage { get; set; }

    public bool? TeamEnabled { get; set; }

    public int? TeamMemberPerEvent { get; set; }

    public DateTime? LastUpdated { get; set; }

    public bool? LiveHidden { get; set; }

    public string Announcements { get; set; }

    public Guid? ClubId { get; set; }

    public Guid? WaiverDocumentId { get; set; }

    public string SeasonDescription { get; set; }

    public string ClubDescription { get; set; }
}