// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VLiPcloudMessage
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid LiPcloudMessageId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public int? Status { get; set; }

    public string Error { get; set; }

    public Guid? UserId { get; set; }

    public DateTime? CreationDate { get; set; }

    public DateTime? StatusDate { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public Guid? ReferenceId { get; set; }

    public string ReferenceDescription { get; set; }

    public string EntityName { get; set; }

    public string Username { get; set; }

    public string UserDescription { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public Guid? ServerId { get; set; }

    public string ServerName { get; set; }

    public string ServerDescription { get; set; }

    public string HardwareId { get; set; }
}