// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VMembershipAffiliation
{
    public Guid Id { get; set; }

    public Guid MembershipAffiliationId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public decimal? TotalFeeAmount { get; set; }

    public decimal? TotalPaidFeeAmount { get; set; }

    public DateTime? CreationDate { get; set; }

    public Guid PlayerId { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid? MembershipCardTypeId { get; set; }

    public string MembershipCardTypeDescription { get; set; }

    public string MembershipCardTypeCode { get; set; }

    public int? Color { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public Guid UserId { get; set; }

    public string UserDescription { get; set; }

    public string Username { get; set; }
}