// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VMenuItem
{
    public Guid Id { get; set; }

    public Guid MenuItemId { get; set; }

    public string MenuKey { get; set; }

    public string MenuAction { get; set; }

    public string MenuParameters { get; set; }

    public string DefaultDescription { get; set; }

    public string DefaultImage { get; set; }

    public int MenuType { get; set; }

    public string Uitype { get; set; }

    public string UipageType { get; set; }

    public Guid? EntityId { get; set; }

    public Guid? ViewId { get; set; }

    public bool Marketing { get; set; }

    public Guid? ContactTypeId { get; set; }

    public bool? RunAsNewThread { get; set; }

    public int? PermissionFlags { get; set; }

    public int? Flags { get; set; }
}