// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VMenuLocalized
{
    public Guid MenuId { get; set; }

    public Guid? ParentId { get; set; }

    public string DefaultDescription { get; set; }

    public string DefaultImage { get; set; }

    public int? Position { get; set; }

    public Guid? Id { get; set; }

    public string Language { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }
}