// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VOlapviewSchema
{
    public Guid Id { get; set; }

    public Guid OlapviewSchemaId { get; set; }

    public string Description { get; set; }

    public string Comments { get; set; }

    public Guid? OlapviewId { get; set; }

    public int? Type { get; set; }

    public byte[] Content { get; set; }
}