// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPaymentModality
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid? CurrencyId { get; set; }

    public Guid PaymentModalityId { get; set; }

    public string PaymentModalityDescription { get; set; }

    public int? PaymentTypeId { get; set; }

    public int? OrderIndex { get; set; }

    public decimal? DefaultCreditAmount { get; set; }

    public bool? TournamentAllowed { get; set; }

    public bool? TournamentPayoutAllowed { get; set; }

    public bool? TournamentTicketCashoutAllowed { get; set; }

    public bool? BarAllowed { get; set; }

    public byte[] Image { get; set; }

    public bool? Reserved { get; set; }

    public bool? CashAllowed { get; set; }

    public bool? CashOutAllowed { get; set; }

    public bool? LiveVisible { get; set; }

    public Guid? OwnerId { get; set; }

    public string CurrencyDescription { get; set; }

    public string CurrencySymbol { get; set; }

    public string CurrencyCode { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}