// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPaymentModalityPerPlayer
{
    public Guid Id { get; set; }

    public Guid PaymentModalityPerPlayerId { get; set; }

    public Guid? PaymentModalityId { get; set; }

    public Guid? PlayerId { get; set; }

    public DateTimeOffset? CreationDate { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string CardNumber { get; set; }

    public string Fullname { get; set; }

    public string PaymentModalityDescription { get; set; }
}