// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPaymentType
{
    public string PaymentTypeDescription { get; set; }

    public Guid PaymentTypeId { get; set; }

    public string Code { get; set; }

    public Guid Id { get; set; }

    public string Description { get; set; }
}