// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPlayerHistory
{
    public Guid PlayerHistoryId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid? UserId { get; set; }

    public byte[] Content { get; set; }

    public DateTimeOffset? CreationDate { get; set; }

    public Guid? ServerId { get; set; }

    public string Username { get; set; }

    public string UserFullname { get; set; }

    public string ServerName { get; set; }

    public string ServerDescription { get; set; }

    public string HardwareId { get; set; }
}