// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPlayerAlert
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public Guid PlayerAlertId { get; set; }

    public string Reason { get; set; }

    public Guid? PlayerId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? Expiration { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public Guid? ReferenceItemId { get; set; }

    public string ReferenceDescription { get; set; }

    public Guid? ReferenceParentId { get; set; }

    public Guid? UserId { get; set; }

    public DateTime? LastUpdated { get; set; }

    public int? TypeId { get; set; }

    public string Note { get; set; }

    public bool? Banned { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public Guid? SeasonId { get; set; }

    public string SeasonDescription { get; set; }

    public string LeagueDescription { get; set; }

    public string PlayerDescription { get; set; }

    public string UserDescription { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}