// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPlayerAccount
{
    public Guid Id { get; set; }

    public Guid PlayerAccountId { get; set; }

    public Guid? AccountTypeId { get; set; }

    public Guid? PlayerId { get; set; }

    public decimal? Balance { get; set; }

    public decimal? BalanceNotWithdrawable { get; set; }

    public string AccountTypeDescription { get; set; }

    public decimal? CreditAmount { get; set; }

    public string Remarks { get; set; }

    public bool? Reserved { get; set; }

    public int? PaymentTypeId { get; set; }

    public Guid? CurrencyId { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public string PlayerDescription { get; set; }
}