// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPlayer
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid PlayerId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string NickName { get; set; }

    public string IdentityCode { get; set; }

    public DateTime? BirthDate { get; set; }

    public string City { get; set; }

    public Guid? PhotoId { get; set; }

    public string Address { get; set; }

    public string State { get; set; }

    public Guid? CountryId { get; set; }

    public byte[] Photo { get; set; }

    public bool EmailNotify { get; set; }

    public bool Smsnotify { get; set; }

    public double? BuyinStart { get; set; }

    public double? BuyinEnd { get; set; }

    public string Email { get; set; }

    public string CardNumber { get; set; }

    public Guid? CardTypeId { get; set; }

    public string Cell { get; set; }

    public string Phone { get; set; }

    public DateTime? CreationDate { get; set; }

    public string DocumentType { get; set; }

    public string DocumentNumber { get; set; }

    public Guid? SponsorId { get; set; }

    public string ZipCode { get; set; }

    public int? Gender { get; set; }

    public bool? NetworkApproved { get; set; }

    public Guid? NetworkUniqueId { get; set; }

    public DateTime? NetworkLastDownload { get; set; }

    public DateTime? CardExpiration { get; set; }

    public DateTime? DocumentExpiration { get; set; }

    public bool? DocumentVerified { get; set; }

    public string Identifier { get; set; }

    public DateTime? NetworkLastUpload { get; set; }

    public DateTime? LastUpdated { get; set; }

    public string BirthPlace { get; set; }

    public bool? PrivacyAgree { get; set; }

    public bool? PrivacyHidePhoto { get; set; }

    public int? AlertFlags { get; set; }

    public Guid? ClubId { get; set; }

    public string Source { get; set; }

    public int? Status { get; set; }

    public DateTime? BlankOutRequest { get; set; }

    public DateTime? BlankOutCompleted { get; set; }

    public string Account { get; set; }

    public DateTime? AccountDate { get; set; }

    public string Note { get; set; }

    public DateTime? PersonalDataLastUpdated { get; set; }

    public string InternalIdentifier { get; set; }

    public int? CategoryId { get; set; }

    public string PreferredName { get; set; }

    public DateTime? BlackListOverride { get; set; }

    public Guid? ServerId { get; set; }

    public DateTime? PrivacyAgreeFrom { get; set; }

    public Guid? CreationUserId { get; set; }

    public Guid? LastUpdateUserId { get; set; }

    public string ViplevelDescription { get; set; }

    public int? ViplevelIndex { get; set; }

    public int? ViplevelColor { get; set; }

    public string CountryDescription { get; set; }

    public string CountryCode { get; set; }

    public string SponsorDescription { get; set; }
}