// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPlayerTicket
{
    public string Description { get; set; }

    public Guid TicketId { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? Expiration { get; set; }

    public decimal? Value { get; set; }

    public bool WithdrawAllowed { get; set; }

    public Guid? TransactionTypeId { get; set; }

    public Guid TicketTypeId { get; set; }

    public int Used { get; set; }

    public bool? Withdrawed { get; set; }

    public Guid? TournamentId { get; set; }

    public string TournamentDescription { get; set; }

    public int SatelliteType { get; set; }

    public Guid PlayerId { get; set; }

    public string PlayerDescription { get; set; }

    public string CardNumber { get; set; }

    public DateTime? CardExpiration { get; set; }

    public string Email { get; set; }

    public Guid? CountryId { get; set; }

    public int? Gender { get; set; }

    public Guid UserId { get; set; }

    public string Username { get; set; }

    public DateTime? Tcdate { get; set; }

    public Guid? TctransactionTypeId { get; set; }

    public Guid? TcuserId { get; set; }

    public Guid? TcreferenceTypeId { get; set; }

    public Guid? TcreferenceId { get; set; }

    public Guid? TcreferenceItemId { get; set; }

    public string TcreferenceDescription { get; set; }
}