// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPlayerTournamentResult
{
    public Guid TournamentId { get; set; }

    public string TournamentDescription { get; set; }

    public DateTime? StartDate { get; set; }

    public int? TournamentTypeId { get; set; }

    public int? TournamentPlayerCount { get; set; }

    public Guid? ClubId { get; set; }

    public Guid TournamentPlayerId { get; set; }

    public bool? Itm { get; set; }

    public bool? ReEntry { get; set; }

    public bool? Punctuality { get; set; }

    public decimal? Buyin { get; set; }

    public decimal? Fee { get; set; }

    public double? PayoutAmount { get; set; }

    public decimal? KnockOutAmount { get; set; }

    public int? KnockOutCount { get; set; }

    public decimal? HouseAmount { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? RebuyAmount { get; set; }

    public decimal? RebuyFee { get; set; }

    public int? RebuyCount { get; set; }

    public decimal? AddonAmount { get; set; }

    public decimal? AddonFee { get; set; }

    public int? AddonCount { get; set; }

    public decimal? DoubleChanceAmount { get; set; }

    public decimal? DoubleChanceFee { get; set; }

    public int? DoubleChanceCount { get; set; }

    public decimal? BuyinAmount { get; set; }

    public decimal? FeeAmount { get; set; }

    public decimal? TotalPayoutKnockOutAmount { get; set; }

    public double? TotalPayoutAmount { get; set; }

    public decimal? SpentAmount { get; set; }

    public decimal? TotalTicketBonusAmount { get; set; }

    public decimal? TotalPayoutTicketAmount { get; set; }

    public decimal? ProfitAmount { get; set; }

    public int? Status { get; set; }

    public decimal? Roi { get; set; }

    public int? EliminationPosition { get; set; }

    public Guid PlayerId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string PlayerDescription { get; set; }

    public DateTime? BirthDate { get; set; }

    public string NickName { get; set; }

    public int? Gender { get; set; }

    public Guid? CountryId { get; set; }

    public string CountryDescription { get; set; }

    public string Code { get; set; }

    public Guid? SeasonId { get; set; }

    public string SeasonDescription { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public Guid? SponsorId { get; set; }

    public string SponsorDescription { get; set; }

    public int? TournamentStatus { get; set; }
}