// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPlayerVip
{
    public Guid Id { get; set; }

    public Guid PlayerId { get; set; }

    public Guid? VipcampaignId { get; set; }

    public Guid? ViplevelId { get; set; }

    public DateTime? Vipdate { get; set; }

    public decimal? VipmonthlyBalance { get; set; }

    public decimal? VipyearlyBalance { get; set; }

    public decimal? Vipbalance { get; set; }

    public int? ViplevelUngainedMonths { get; set; }
}