// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPlayerLastAccess
{
    public DateTime? Date { get; set; }

    public Guid? PlayerId { get; set; }

    public string Type { get; set; }
}