// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VPlayerDomain
{
    public Guid Id { get; set; }

    public Guid DomainId { get; set; }

    public Guid PlayerId { get; set; }

    public Guid PlayerDomainId { get; set; }

    public Guid? MemberId { get; set; }

    public string MemberCardId { get; set; }

    public DateTimeOffset? Date { get; set; }

    public Guid? UserId { get; set; }

    public string Username { get; set; }

    public string UserDescription { get; set; }

    public string DomainDescription { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}