// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VRankingManual
{
    public Guid? RankingId { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public Guid? TournamentId { get; set; }

    public DateTime? Date { get; set; }

    public string Description { get; set; }
}