// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VRankingReward
{
    public long? Position { get; set; }

    public string Description { get; set; }

    public decimal? Value { get; set; }

    public byte[] Image { get; set; }

    public string Period { get; set; }

    public int? Year { get; set; }

    public int? Month { get; set; }

    public Guid RankingId { get; set; }

    public string RankingDescription { get; set; }

    public int? MaxEventCount { get; set; }

    public Guid PlayerId { get; set; }

    public int? Gender { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string PlayerDescription { get; set; }

    public string NickName { get; set; }

    public string CardNumber { get; set; }

    public DateTime? BirthDate { get; set; }

    public string Email { get; set; }

    public Guid? SponsorId { get; set; }

    public Guid? CountryId { get; set; }

    public string CountryDescription { get; set; }

    public string CountryCode { get; set; }
}