// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VRankingPeriod
{
    public Guid? RankingId { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public string Period { get; set; }
}