// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VRankingPlayer
{
    public string Period { get; set; }

    public long? Position { get; set; }

    public long? PreviousPosition { get; set; }

    public decimal? Points { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public decimal? PointsTrend { get; set; }

    public long? PositionTrend { get; set; }

    public decimal? PreviousPoints { get; set; }

    public long? EventCount { get; set; }

    public long? PreviousEventCount { get; set; }

    public int? FinalTableCount { get; set; }

    public int? InTheMoneyCount { get; set; }

    public decimal? TotalWinAmount { get; set; }

    public int? WinsCount { get; set; }

    public Guid RankingId { get; set; }

    public string RankingDescription { get; set; }

    public int? MaxEventCount { get; set; }

    public string RewardDescription { get; set; }

    public decimal? RewardValue { get; set; }

    public Guid PlayerId { get; set; }

    public int? Gender { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string PlayerDescription { get; set; }

    public string NickName { get; set; }

    public string CardNumber { get; set; }

    public DateTime? BirthDate { get; set; }

    public string Email { get; set; }

    public Guid? SponsorId { get; set; }

    public Guid? CountryId { get; set; }

    public string CountryDescription { get; set; }

    public string CountryCode { get; set; }
}