// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VRankingTournament
{
    public Guid? RankingId { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public Guid TournamentId { get; set; }

    public DateTime? Date { get; set; }

    public string Description { get; set; }

    public int? TotalPlayersCount { get; set; }

    public double? Buyin { get; set; }

    public double? Fee { get; set; }

    public int? Behavior { get; set; }

    public bool KnockOut { get; set; }

    public bool? Rebuy { get; set; }

    public bool? Addon { get; set; }

    public int? TournamentTypeId { get; set; }

    public decimal? TotalAmount { get; set; }

    public string ClubDescription { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public string SeasonDescription { get; set; }
}