// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VRankingSponsor
{
    public long? Position { get; set; }

    public Guid SponsorId { get; set; }

    public string SponsorDescription { get; set; }

    public decimal? Points { get; set; }

    public int? Players { get; set; }

    public Guid RankingId { get; set; }

    public string RankingDescription { get; set; }

    public int? Year { get; set; }

    public int? Month { get; set; }
}