// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VRankingPlayerPoint
{
    public Guid? RankingId { get; set; }

    public DateTime? Date { get; set; }

    public decimal? Points { get; set; }

    public decimal? AssignedPoints { get; set; }

    public decimal? ManualPoints { get; set; }

    public int? Position { get; set; }

    public bool? FinalTable { get; set; }

    public bool? Itm { get; set; }

    public decimal? TotalWinning { get; set; }

    public int? TotalEntries { get; set; }

    public string Error { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public string Description { get; set; }

    public Guid? EntityId { get; set; }

    public double? KnockOutAmount { get; set; }

    public bool? KnockOut { get; set; }

    public string Category { get; set; }

    public string EntityDescription { get; set; }

    public string SeasonDescription { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public Guid? ClubId { get; set; }

    public string CurrencyDescription { get; set; }

    public string CurrencySymbol { get; set; }

    public string ClubDescription { get; set; }

    public double? PlayTotalMinutes { get; set; }

    public decimal? BuyinFee { get; set; }

    public int? Entries { get; set; }

    public Guid PlayerId { get; set; }

    public int? Gender { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string PlayerDescription { get; set; }

    public string NickName { get; set; }

    public string CardNumber { get; set; }

    public DateTime? BirthDate { get; set; }

    public string Email { get; set; }

    public Guid? SponsorId { get; set; }

    public Guid? CountryId { get; set; }

    public string CountryDescription { get; set; }

    public string CountryCode { get; set; }

    public string RankingDescription { get; set; }

    public int? TotalEventCount { get; set; }

    public int? TotalPlayerCount { get; set; }
}