// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VRankingPlayerPointsPerTournament
{
    public Guid RankingPlayerPointsId { get; set; }

    public Guid? RankingId { get; set; }

    public DateTime? Date { get; set; }

    public decimal? Points { get; set; }

    public string Error { get; set; }

    public int? Month { get; set; }

    public int? Year { get; set; }

    public int? Position { get; set; }

    public bool? Itm { get; set; }

    public bool? FinalTable { get; set; }

    public decimal? AssignedPoints { get; set; }

    public decimal? ManualPoints { get; set; }

    public decimal? TotalPayoutAmount { get; set; }

    public string Description { get; set; }

    public Guid PlayerId { get; set; }

    public int? Gender { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string PlayerDescription { get; set; }

    public string NickName { get; set; }

    public string CardNumber { get; set; }

    public DateTime? BirthDate { get; set; }

    public string Email { get; set; }

    public Guid? SponsorId { get; set; }

    public Guid? CountryId { get; set; }

    public string CountryDescription { get; set; }

    public string CountryCode { get; set; }

    public Guid TournamentId { get; set; }

    public string TournamentDescription { get; set; }

    public int? TotalPlayersCount { get; set; }

    public double? Buyin { get; set; }

    public double? Fee { get; set; }

    public int? Behavior { get; set; }

    public bool KnockOut { get; set; }

    public bool? Rebuy { get; set; }

    public bool? Addon { get; set; }

    public int? TournamentTypeId { get; set; }

    public int? Entries { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}