// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VReport
{
    public Guid Id { get; set; }

    public Guid ReportId { get; set; }

    public string Image { get; set; }

    public string RecordSelectionFormula { get; set; }

    public string Filter { get; set; }

    public string Classname { get; set; }

    public string SearchText { get; set; }
}