// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VServer
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid ServerId { get; set; }

    public string ServerDescription { get; set; }

    public string ServerName { get; set; }

    public string HardwareId { get; set; }

    public string Code { get; set; }

    public DateTime? LastAccess { get; set; }

    public string Version { get; set; }

    public long? VersionNumber { get; set; }

    public string VersionType { get; set; }

    public string VersionReleaseId { get; set; }

    public DateTime? InstallationDate { get; set; }
}