// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VSetting
{
    public Guid SettingsId { get; set; }

    public Guid? CashReportId { get; set; }

    public bool? CashTouchScreenPrintTicket { get; set; }

    public int? CashTouchScreenTimeout { get; set; }

    public Guid? TournamentReportId { get; set; }

    public Guid? TournamentPayoutId { get; set; }

    public Guid? SitngoPayoutId { get; set; }

    public int? CardParseType { get; set; }

    public int? CardFieldPosition { get; set; }

    public int? CardFieldLength { get; set; }

    public string CardFieldSeparator { get; set; }

    public int? MembershipCardAutoPrint { get; set; }

    public Guid? MembershipCardReportId { get; set; }
}