// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VSponsor
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public Guid SponsorId { get; set; }

    public string SponsorDescription { get; set; }

    public byte[] Image { get; set; }

    public string SearchText { get; set; }

    public Guid? ClubId { get; set; }
}