// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VStcashPlayer
{
    public Guid? PlayerId { get; set; }

    public DateTime? LastSubscription { get; set; }

    public int? Subscription { get; set; }

    public double? TotalMinutesPlayed { get; set; }

    public int? CashTypeCount { get; set; }
}