// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VStcashSessionType
{
    public Guid CashSessionId { get; set; }

    public Guid? CashTypeId { get; set; }

    public int? TableCount { get; set; }

    public int? TotalMinutesPlayed { get; set; }

    public double? TotalRake { get; set; }
}