// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VStcash
{
    public Guid CashSessionId { get; set; }

    public DateTime? Date { get; set; }

    public DateTime? BeginDate { get; set; }

    public DateTime? EndDate { get; set; }

    public double? TotalRake { get; set; }

    public int? TableCount { get; set; }

    public int? TotalOpeningMinutes { get; set; }

    public int? PlayerCount { get; set; }

    public double? TotalMinutesPlayed { get; set; }

    public double? Vippoints { get; set; }

    public Guid CashTypeId { get; set; }

    public double? SmallBlind { get; set; }

    public double? BigBlind { get; set; }

    public int? SitCount { get; set; }

    public Guid? SeasonId { get; set; }

    public string SeasonDescription { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public string SeasonLeagueDescription { get; set; }
}