// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VStplayer
{
    public Guid PlayerId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public Guid? SponsorId { get; set; }

    public Guid TournamentPlayerId { get; set; }

    public Guid TournamentId { get; set; }

    public bool? Itm { get; set; }

    public string TournamentDescription { get; set; }

    public DateTime? StartDate { get; set; }

    public double? Buyin { get; set; }

    public double? RebuyAmount { get; set; }

    public double? Fee { get; set; }

    public double? RebuyFee { get; set; }

    public double? AddonAmount { get; set; }

    public double? AddonFee { get; set; }

    public double? KnockOutAmount { get; set; }

    public Guid? SeasonId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public bool Addon { get; set; }

    public int? RebuyCount { get; set; }

    public int? Position { get; set; }

    public double? PayoutAmount { get; set; }

    public double? Points { get; set; }

    public double? LeaguePoints { get; set; }

    public string CountryDescription { get; set; }

    public DateTime? BirthDate { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public string SeasonDescription { get; set; }

    public int? KnockOutCount { get; set; }

    public int? TournamentStatus { get; set; }

    public int? TournamentTypeId { get; set; }

    public int? TournamentPlayerCount { get; set; }

    public string SponsorDescription { get; set; }

    public byte[] SponsorImageContent { get; set; }

    public decimal? TotalHouseContribution { get; set; }

    public decimal? TotalTax { get; set; }
}