// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VSttournament
{
    public Guid TournamentId { get; set; }

    public Guid? ClubId { get; set; }

    public string TournamentDescription { get; set; }

    public DateTime? StartDate { get; set; }

    public double? Buyin { get; set; }

    public double? Fee { get; set; }

    public double? KnockOutAmount { get; set; }

    public Guid? SeasonId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public int? TournamentStatus { get; set; }

    public int? TournamentTypeId { get; set; }

    public int? MaxEntriesPerPlayer { get; set; }

    public int? TotalPayoutsCount { get; set; }

    public Guid? GameTypeId { get; set; }

    public int? Behavior { get; set; }

    public Guid? TournamentTemplateId { get; set; }

    public int? ReEntries { get; set; }

    public decimal? TotalKnockOut { get; set; }

    public decimal? TotalBuyin { get; set; }

    public int? TotalRebuysCount { get; set; }

    public decimal? TotalRebuy { get; set; }

    public decimal? TotalRebuyFee { get; set; }

    public int? TotalAddonsCount { get; set; }

    public decimal? TotalAddon { get; set; }

    public decimal? TotalAddonFee { get; set; }

    public int? TotalDoubleChancesCount { get; set; }

    public decimal? TotalDoubleChance { get; set; }

    public decimal? TotalDoubleChanceFee { get; set; }

    public decimal? TotalHouseContribution { get; set; }

    public decimal? TotalFee { get; set; }

    public decimal? TotalTax { get; set; }

    public decimal? TotalAdditional { get; set; }

    public decimal? TotalChips { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? TotalUnassignedAmount { get; set; }

    public int? TotalPlayersCount { get; set; }

    public int? TotalBuyinCount { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public string SeasonDescription { get; set; }
}