// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTeam
{
    public Guid Id { get; set; }

    public Guid TeamId { get; set; }

    public string TeamDescription { get; set; }

    public string SearchText { get; set; }

    public Guid? SeasonId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public int? TotalMembers { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}