// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTemplateLevel
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid TemplateLevelId { get; set; }

    public string TemplateLevelDescription { get; set; }

    public DateTime? LastUpdate { get; set; }

    public string Note { get; set; }

    public string Url { get; set; }

    public int? LevelsAnteType { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}