// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTemplateDescription
{
    public Guid Id { get; set; }

    public Guid TemplateDescriptionId { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public string Note { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}