// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTemplatePayout
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid TemplatePayoutId { get; set; }

    public string TemplatePayoutDescription { get; set; }

    public DateTime? LastUpdate { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}