// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentLog
{
    public Guid TournamentActionId { get; set; }

    public Guid Id { get; set; }

    public Guid? TournamentPlayerId { get; set; }

    public Guid? PlayerId { get; set; }

    public long? Ticket { get; set; }

    public string TournamentPlayerLastname { get; set; }

    public string TournamentPlayerFirstname { get; set; }

    public Guid? PreviousTableId { get; set; }

    public int PreviousTableIndex { get; set; }

    public int PreviousTableSeatIndex { get; set; }

    public Guid? PreviousLevelId { get; set; }

    public int PreviousLevelIndex { get; set; }

    public double PreviousLevelDuration { get; set; }

    public double PreviousLevelElapsedTime { get; set; }

    public Guid? CurrentTableId { get; set; }

    public int CurrentTableIndex { get; set; }

    public int CurrentTableSeatIndex { get; set; }

    public Guid? CurrentLevelId { get; set; }

    public int CurrentLevelIndex { get; set; }

    public double CurrentLevelElapsedTime { get; set; }

    public double CurrentLevelDuration { get; set; }

    public int ActionType { get; set; }

    public DateTime ActionDateTime { get; set; }

    public Guid UserId { get; set; }

    public string UserLastname { get; set; }

    public string UserFirstname { get; set; }

    public string UserUsername { get; set; }

    public string CurrentGroup { get; set; }

    public string PreviousGroup { get; set; }

    public DateTime? StartDate { get; set; }

    public string TournamentDescription { get; set; }

    public int? TournamentTypeId { get; set; }

    public Guid? GameTypeId { get; set; }

    public Guid? SeasonId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public Guid? TournamentParentId { get; set; }

    public Guid? TournamentTemplateId { get; set; }

    public int? TournamentStatus { get; set; }

    public Guid? ClubId { get; set; }
}