// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentPlayerEntry
{
    public Guid Id { get; set; }

    public string Type { get; set; }

    public DateTime? SubscriptionDate { get; set; }

    public Guid PlayerId { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid TournamentId { get; set; }

    public string TournamentDescription { get; set; }

    public DateTime? TournamentStartDate { get; set; }

    public int? TournamentNumber { get; set; }

    public bool? TournamentSingleDay { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public Guid? SeasonId { get; set; }

    public string SeasonDescription { get; set; }

    public int? TournamentDay { get; set; }

    public string TournamentGroup { get; set; }

    public bool? Summary { get; set; }

    public Guid? ServerId { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public string AuthorizationId { get; set; }

    public string CurrencySymbol { get; set; }

    public double? SubscriptionAmount { get; set; }

    public Guid? DomainId { get; set; }

    public Guid? DomainMemberId { get; set; }

    public string DomainMemberCardId { get; set; }
}