// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentLayout
{
    public Guid Id { get; set; }

    public string SearchText { get; set; }

    public string Description { get; set; }

    public Guid TournamentLayoutId { get; set; }

    public string TournamentLayoutDescription { get; set; }

    public string Content { get; set; }

    public int? ScreenWidth { get; set; }

    public int? ScreenHeight { get; set; }

    public byte[] Layout { get; set; }

    public bool? Hidden { get; set; }

    public byte[] Image { get; set; }

    public bool Reserved { get; set; }

    public int? LayoutTipology { get; set; }

    public Guid? StoreId { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}