// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentPlayersCalculationDatum
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public DateTime? Date { get; set; }

    public Guid? TournamentParentId { get; set; }

    public int? ChildCount { get; set; }

    public Guid TournamentId { get; set; }

    public string TournamentDescription { get; set; }

    public DateTime? StartDate { get; set; }

    public Guid? SeasonId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public int? TournamentNumber { get; set; }

    public int? PlayersCount { get; set; }

    public int? TotalRebuysCount { get; set; }

    public int? TotalAddonsCount { get; set; }

    public int? TotalDoubleChancesCount { get; set; }

    public decimal? TotalBuyinAmount { get; set; }

    public decimal? TotalFeeAmount { get; set; }

    public decimal? TotalRebuysAmount { get; set; }

    public decimal? TotalRebuysFeeAmount { get; set; }

    public decimal? TotalAddonsAmount { get; set; }

    public decimal? TotalAddonsFeeAmount { get; set; }

    public decimal? TotalDoubleChancesAmount { get; set; }

    public decimal? TotalDoubleChancesFeeAmount { get; set; }

    public double? KnockOut { get; set; }

    public int? PayoutsCount { get; set; }

    public string TournamentTag { get; set; }

    public int? Days { get; set; }

    public bool HasKnockOut { get; set; }

    public int? ReEntriesCount { get; set; }

    public decimal? TotalAmount { get; set; }

    public string CurrencySymbol { get; set; }

    public string CurrencyDescription { get; set; }

    public int? TournamentTypeId { get; set; }

    public int? Entries { get; set; }

    public DateTime? CompletionDate { get; set; }

    public Guid ReferenceId { get; set; }

    public string ReferenceDescription { get; set; }

    public bool? Sat { get; set; }

    public int EventTypeId { get; set; }

    public string ReferenceTypeId { get; set; }

    public Guid ReferenceItemId { get; set; }

    public DateTimeOffset? ReferenceDate { get; set; }

    public bool? Punctuality { get; set; }

    public int? RebuysCount { get; set; }

    public int? AddonsCount { get; set; }

    public int? DoubleChancesCount { get; set; }

    public double? KnockOutCount { get; set; }

    public decimal? Buyin { get; set; }

    public decimal? BuyinFee { get; set; }

    public int? LevelIndex { get; set; }

    public int? EliminationLevelIndex { get; set; }

    public int? EliminationDay { get; set; }

    public string EliminationGroup { get; set; }

    public DateTimeOffset? EliminationDate { get; set; }

    public DateTimeOffset? SubscriptionDate { get; set; }

    public int? SubscriptionDay { get; set; }

    public string SubscriptionGroup { get; set; }

    public int? SubscriptionLevelIndex { get; set; }

    public decimal? TotalCost { get; set; }

    public decimal? TicketBonusAmount { get; set; }

    public double? PayoutAmount { get; set; }

    public int? PlayerEntries { get; set; }

    public Guid TournamentPlayerId { get; set; }

    public Guid? PlayerId { get; set; }

    public Guid ItemId { get; set; }

    public bool? Qualified { get; set; }

    public decimal? PlayerHouseAmount { get; set; }

    public decimal? PlayerTaxAmount { get; set; }

    public decimal? PlayerRebuyHouseAmount { get; set; }

    public decimal? PlayerAddonHouseAmount { get; set; }

    public decimal? PlayerRebuyTaxAmount { get; set; }

    public decimal? PlayerAddonTaxAmount { get; set; }

    public decimal? PlayerDoubleChanceHouseAmount { get; set; }

    public decimal? PlayerDoubleChanceTaxAmount { get; set; }

    public decimal? PlayerRebuyAmount { get; set; }

    public decimal? PlayerRebuyFee { get; set; }

    public decimal? PlayerAddonAmount { get; set; }

    public decimal? PlayerDoubleChanceAmount { get; set; }

    public DateTime? LastUpdated { get; set; }

    public bool? Itm { get; set; }

    public decimal? PrizeWinning { get; set; }

    public double? TotalWinning { get; set; }

    public decimal? TotalPayoutAmount { get; set; }

    public decimal? TotalPayoutAmountOriginal { get; set; }

    public bool? PayoutDeal { get; set; }

    public bool? IsFinalTable { get; set; }

    public decimal? PlayerTotalRebuyAmount { get; set; }

    public decimal? PlayerTotalRebuyFee { get; set; }

    public decimal? PlayerTotalAddonAmount { get; set; }

    public decimal? PlayerTotalAddonFee { get; set; }

    public decimal? PlayerTotalDoubleChanceAmount { get; set; }

    public decimal? PlayerTotalDoubleChanceFee { get; set; }

    public int? PlayerTotalEntries { get; set; }

    public decimal? PlayerTotalBuyin { get; set; }

    public decimal? PlayerTotalFee { get; set; }

    public decimal? PlayerAddonFee { get; set; }

    public decimal? PlayerTotalReEntryBuyin { get; set; }

    public decimal? PlayerTotalReEntryFee { get; set; }

    public decimal? PlayerDoubleChanceFee { get; set; }

    public double? PlayerTotalKnockOutCount { get; set; }

    public int? PlayerTotalRebuysCount { get; set; }

    public int? PlayerTotalAddonsCount { get; set; }

    public int? PlayerTotalDoubleChancesCount { get; set; }

    public decimal? BuyinFeeMax { get; set; }

    public DateTimeOffset? FirstSubscriptionDate { get; set; }

    public DateTimeOffset? LastSubscriptionDate { get; set; }

    public int? UniquePosition { get; set; }

    public int? UniquePlayersCount { get; set; }

    public string SeasonDescription { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public string MembershipCardTypeCode { get; set; }

    public string MembershipCardTypeDescription { get; set; }

    public string GameTypeCode { get; set; }

    public string GameTypeDescription { get; set; }

    public int? Sex { get; set; }

    public string SponsorDescription { get; set; }

    public Guid? PromotionId { get; set; }

    public int? Position { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public string ClubCode { get; set; }
}