// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentTheme
{
    public Guid Id { get; set; }

    public string SearchText { get; set; }

    public string Description { get; set; }

    public int? Color { get; set; }

    public int? ColorContrast { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}