// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentBillboard
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid TournamentBillboardId { get; set; }

    public string TournamentBillboardDescription { get; set; }

    public DateTime? BeginDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool? IncludeCompleted { get; set; }

    public bool? ShowOnlySubscriptionOpened { get; set; }

    public Guid? SeasonId { get; set; }

    public string SeasonDescription { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public Guid? ServerId { get; set; }
}