// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentPlayer
{
    public int? Position { get; set; }

    public Guid TournamentId { get; set; }

    public Guid TournamentPlayerId { get; set; }

    public Guid? PlayerId { get; set; }

    public int? Status { get; set; }

    public DateTimeOffset? PayoutDate { get; set; }

    public bool? PayoutAssigned { get; set; }

    public double? PayoutAmount { get; set; }

    public decimal? PayoutKnockOutAmount { get; set; }

    public Guid? PayoutTicketId { get; set; }

    public Guid? ReferenceId { get; set; }

    public int? Entries { get; set; }

    public Guid? PayoutUserId { get; set; }

    public int? Entry { get; set; }

    public int? EntryDay { get; set; }

    public decimal? Buyin { get; set; }

    public decimal? Fee { get; set; }

    public int? Ticket { get; set; }

    public long? WaitingTicket { get; set; }

    public int? TableIndex { get; set; }

    public int? SeatIndex { get; set; }

    public DateTimeOffset? SubscriptionDate { get; set; }

    public int? SubscriptionDay { get; set; }

    public string SubscriptionGroup { get; set; }

    public string SubscriptionDayDescription { get; set; }

    public decimal? SubscriptionTotalDue { get; set; }

    public string SubscriptionPaymentDescription { get; set; }

    public double? ChipsCount { get; set; }

    public int? TournamentTableIndex { get; set; }

    public int? TournamentTableSeatIndex { get; set; }

    public double? KnockOutValue { get; set; }

    public double? KnockOutAmount { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public DateTime? BirthDate { get; set; }

    public string CountryDescription { get; set; }

    public string CountryCode { get; set; }

    public string PlayerDescription { get; set; }

    public string CardNumber { get; set; }

    public string Note { get; set; }

    public string Email { get; set; }

    public string NickName { get; set; }

    public string Account { get; set; }

    public string Source { get; set; }

    public string Identifier { get; set; }

    public string SubscriptionUsername { get; set; }

    public string SubscriptionUserDescription { get; set; }

    public string PayoutUsername { get; set; }

    public string PayoutUserDescription { get; set; }
}