// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentThemeAspect
{
    public Guid Id { get; set; }

    public Guid TournamentThemeAspectId { get; set; }

    public Guid? TournamentThemeId { get; set; }

    public decimal? WidthRatio { get; set; }

    public decimal? HeightRatio { get; set; }

    public decimal? Ratio { get; set; }

    public byte[] ViewerAppearanceContent { get; set; }
}