// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentActive
{
    public Guid TournamentActiveId { get; set; }

    public Guid TournamentId { get; set; }

    public DateTime TournamentActivation { get; set; }

    public string HardwareId { get; set; }

    public Guid Id { get; set; }
}