// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentAll
{
    public Guid TournamentId { get; set; }

    public string Description { get; set; }

    public DateTime? StartDate { get; set; }

    public int? PlayerPerTable { get; set; }

    public int? PlayerAllowed { get; set; }

    public double? Chips { get; set; }

    public double? Buyin { get; set; }

    public double? Fee { get; set; }

    public double? BuyinFee { get; set; }

    public double? HouseContribution { get; set; }

    public decimal? ReEntryBuyin { get; set; }

    public decimal? ReEntryFee { get; set; }

    public double? HouseContributionPercentage { get; set; }

    public double? AdditionalAmount { get; set; }

    public double? AdditionalPercentage { get; set; }

    public double? TaxFee { get; set; }

    public double? TaxFeePercentage { get; set; }

    public int? RebuyAllowed { get; set; }

    public int? AddonAllowed { get; set; }

    public bool KnockOut { get; set; }

    public double? KnockOutAmount { get; set; }

    public Guid? CurrencyId { get; set; }

    public bool PayoutsPublished { get; set; }

    public double? GuarantedPayout { get; set; }

    public double? PayoutRoundValue { get; set; }

    public Guid? TemplatePayoutId { get; set; }

    public Guid? TemplatePayoutStructId { get; set; }

    public bool UseTemplatePayout { get; set; }

    public decimal? GuaranteedSpp { get; set; }

    public int? TournamentTypeId { get; set; }

    public Guid? GameTypeId { get; set; }

    public bool AutoSit { get; set; }

    public int? MinimumFreeSeat { get; set; }

    public bool? ReEntryPrizeCustomization { get; set; }

    public Guid? TemplateTicketId { get; set; }

    public int? RegistrationLevelIndex { get; set; }

    public Guid? MainEventId { get; set; }

    public Guid? SeasonId { get; set; }

    public int? SeatAssignmentAlgorithm { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public Guid? CurrentChildId { get; set; }

    public Guid? TournamentParentId { get; set; }

    public int? Day { get; set; }

    public string Group { get; set; }

    public bool LogActionEnabled { get; set; }

    public int? CheckinFlags { get; set; }

    public bool KnockOutTax { get; set; }

    public bool KnockOutHouse { get; set; }

    public int? CurrentDay { get; set; }

    public Guid Id { get; set; }

    public int? Status { get; set; }

    public string SearchText { get; set; }

    public bool? LeaguePointsManually { get; set; }

    public int? MultiEntries { get; set; }

    public int? MaxEntriesPerPlayer { get; set; }

    public int? MaxReEntriesPerPlayer { get; set; }

    public int? TotalPayoutsCount { get; set; }

    public int? TotalPlayersCount { get; set; }

    public int? Behavior { get; set; }

    public Guid? TournamentTemplateId { get; set; }

    public int? ReEntries { get; set; }

    public int? TotalRebuysCount { get; set; }

    public decimal? TotalRebuy { get; set; }

    public decimal? TotalRebuyFee { get; set; }

    public int? TotalAddonsCount { get; set; }

    public decimal? TotalAddon { get; set; }

    public decimal? TotalAddonFee { get; set; }

    public decimal? TotalKnockOut { get; set; }

    public decimal? TotalBuyin { get; set; }

    public decimal? TotalHouseContribution { get; set; }

    public decimal? TotalFee { get; set; }

    public decimal? TotalTax { get; set; }

    public decimal? TotalAdditional { get; set; }

    public decimal? TotalChips { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? TotalUnassignedAmount { get; set; }

    public string AuthorizationId { get; set; }

    public string UploadError { get; set; }

    public string Url { get; set; }

    public DateTime? LastUpload { get; set; }

    public int? TotalIngamePlayersCount { get; set; }

    public Guid? CategoryId { get; set; }

    public bool? AllowCustomization { get; set; }

    public DateTime? LastUpdate { get; set; }

    public decimal? LeagueHouseContributionPercentage { get; set; }

    public Guid? NetworkEventId { get; set; }

    public bool? NetworkEventFinal { get; set; }

    public string PointsCustomFormula { get; set; }

    public string MainEventDescription { get; set; }

    public string MainEventAuthorizationId { get; set; }

    public decimal? MainEventSubscriptionAmount { get; set; }

    public Guid? SeasonLeagueStageId { get; set; }

    public string TableSequenceString { get; set; }

    public double? PunctualityChips { get; set; }

    public DateTime? PunctualityTime { get; set; }

    public int? KnockOutType { get; set; }

    public double? KnockOutProgressive { get; set; }

    public bool? EachDayRequireSubscription { get; set; }

    public bool? EachDayBuyinCustomization { get; set; }

    public bool? Published { get; set; }

    public bool? EnableLockedSeats { get; set; }

    public decimal? SubscriptionSpp { get; set; }

    public decimal? ReEntrySpp { get; set; }

    public int? AddonEndLevelIndex { get; set; }

    public Guid? MainEventTemplateId { get; set; }

    public int? SatelliteType { get; set; }

    public int? SatelliteFormat { get; set; }

    public int? SatelliteMaxWinnableTicketCount { get; set; }

    public long? SatelliteTicketChipsValue { get; set; }

    public bool? PayoutTicketWithdrawable { get; set; }

    public DateTime? PayoutTicketExpire { get; set; }

    public int? KnockOutProgressiveRoundType { get; set; }

    public decimal? KnockOutProgressiveRoundValue { get; set; }

    public Guid? PromotionId { get; set; }

    public int? ChildCount { get; set; }

    public decimal? TotalHouseContributionLeague { get; set; }

    public long? WaitingTicketCounter { get; set; }

    public bool? SingleDay { get; set; }

    public string TableSeatSettingsString { get; set; }

    public long? PlayerTimeRequestTicks { get; set; }

    public Guid? SubscriptionReportId { get; set; }

    public Guid? WaitingReportId { get; set; }

    public Guid? RebuyAddonReportId { get; set; }

    public Guid? PayoutReportId { get; set; }

    public double? HouseContributionValuePerEntry { get; set; }

    public double? LeagueHouseContributionValuePerEntry { get; set; }

    public double? TotalOverlay { get; set; }

    public double? TotalProfit { get; set; }

    public double? TotalAmountEffective { get; set; }

    public double? TotalProfitTax { get; set; }

    public double? ProfitTaxPercentage { get; set; }

    public int? TotalDoubleChancesCount { get; set; }

    public decimal? TotalDoubleChance { get; set; }

    public decimal? TotalDoubleChanceFee { get; set; }

    public bool? DoubleChanceTax { get; set; }

    public bool? DoubleChanceHouse { get; set; }

    public int? DoubleChanceAllowed { get; set; }

    public bool? AllowRebuyAddon { get; set; }

    public int? Number { get; set; }

    public string Tag { get; set; }

    public Guid? ReservationReportId { get; set; }

    public DateTime? SubscriptionOpen { get; set; }

    public DateTime? SubscriptionClose { get; set; }

    public int? LevelDuration { get; set; }

    public int? VisibilityState { get; set; }

    public bool? Summary { get; set; }

    public string BuyinDescription { get; set; }

    public string LevelDescription { get; set; }

    public string Note { get; set; }

    public bool? Flight { get; set; }

    public int? PunctualityLevelIndex { get; set; }

    public int? TotalReservationCount { get; set; }

    public int? TotalUnusedReservationCount { get; set; }

    public int? TotalWaitingCount { get; set; }

    public long? NextWaitingTicketNumber { get; set; }

    public string SeasonDescription { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public Guid? CurrentPromotionId { get; set; }

    public DateTime? CompletionDate { get; set; }

    public int? LevelIndex { get; set; }

    public string ShortDescription { get; set; }

    public bool? ExternalManaged { get; set; }

    public bool? AllowReEntryOnlyOnSubscriptionDay { get; set; }

    public bool? LiveSeatDrawHidden { get; set; }

    public bool? LivePayoutsHidden { get; set; }

    public bool? LiveHidden { get; set; }

    public int? LiveRegistrationType { get; set; }

    public int? LiveReservationSelfRegistrationSeatAssignmentType { get; set; }

    public bool? LiveReservationSelfRegistrationDisabled { get; set; }

    public int? LiveDelayMinutes { get; set; }

    public int? TimeBankCount { get; set; }

    public int? TimeBankFlags { get; set; }

    public int? ElapsedDays { get; set; }

    public int? Days { get; set; }

    public int? UniqueEntries { get; set; }

    public int? UniquePlayers { get; set; }

    public int? Entries { get; set; }

    public Guid? ClubRoomId { get; set; }

    public string Area { get; set; }

    public decimal? AdditionalChips { get; set; }

    public int? AdditionalEntries { get; set; }

    public string DailyDescription { get; set; }

    public string WaitingListNowSeatingText { get; set; }

    public string WaitingListText { get; set; }

    public bool? LiveReservationSelfRegistrationAllowManualSeat { get; set; }

    public decimal? TotalTicketAmount { get; set; }

    public decimal? TotalTicketBonusAmount { get; set; }

    public Guid? ThemeId { get; set; }

    public int? ThemeColor { get; set; }

    public string ThemeDescription { get; set; }

    public string CurrencySymbol { get; set; }

    public string CurrencyDescription { get; set; }

    public string ClubRoomDescription { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }

    public string ClubCode { get; set; }

    public Guid? ServerId { get; set; }

    public string ServerName { get; set; }

    public string ServerDescription { get; set; }

    public string HardwareId { get; set; }
}