// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentRebuyAddon
{
    public Guid TournamentRebuyAddonId { get; set; }

    public Guid? TournamentId { get; set; }

    public Guid? ReferenceId { get; set; }

    public int? TypeId { get; set; }

    public DateTime? Date { get; set; }

    public Guid? UserId { get; set; }

    public decimal? ChipsCount { get; set; }

    public decimal? Paid { get; set; }

    public decimal? Unpaid { get; set; }

    public decimal? Due { get; set; }
}