// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentPlayersCount
{
    public int? TournamentPlayerCount { get; set; }

    public Guid TournamentId { get; set; }
}