// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentRateExpanded
{
    public Guid TournamentId { get; set; }

    public Guid TournamentRateId { get; set; }

    public decimal? RateValue { get; set; }

    public int? Position { get; set; }

    public decimal? OriginalValue { get; set; }

    public bool? Deal { get; set; }

    public decimal? Spp { get; set; }

    public int? Payouts { get; set; }
}