// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentStatus
{
    public Guid TournamentId { get; set; }

    public Guid? TournamentLevelId { get; set; }

    public DateTime? CompletionDate { get; set; }

    public int? Status { get; set; }

    public int? SubscriptionState { get; set; }

    public double? TournamentLevelTimeElapsed { get; set; }

    public DateTime? TournamentLevelTimeLastUpdated { get; set; }

    public int? VisibilityState { get; set; }

    public int? LevelIndex { get; set; }

    public long? LevelDuration { get; set; }

    public long? Duration { get; set; }
}