// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTournamentPlayersBestPlacement
{
    public int? Position { get; set; }

    public Guid TournamentId { get; set; }

    public Guid? PlayerId { get; set; }

    public int? RealPosition { get; set; }

    public int? Entries { get; set; }

    public int? UniquePlayersCount { get; set; }

    public decimal? Buyin { get; set; }

    public decimal? Fee { get; set; }

    public decimal? BuyinFeeMax { get; set; }

    public decimal? ReEntryBuyin { get; set; }

    public decimal? ReEntryFee { get; set; }

    public decimal? RebuyAmount { get; set; }

    public decimal? RebuyFeeAmount { get; set; }

    public decimal? AddonAmount { get; set; }

    public decimal? AddonFeeAmount { get; set; }

    public decimal? DoubleChanceAmount { get; set; }

    public decimal? DoubleChanceFeeAmount { get; set; }

    public int? RebuysCount { get; set; }

    public int? AddonsCount { get; set; }

    public int? DoubleChancesCount { get; set; }

    public double? KnockOutCount { get; set; }

    public decimal? TicketAmount { get; set; }

    public DateTimeOffset? FirstSubscriptionDate { get; set; }

    public DateTimeOffset? LastSubscriptionDate { get; set; }
}