// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTransactionType
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public Guid TransactionTypeId { get; set; }

    public string TransactionTypeDescription { get; set; }

    public int PlayerMultiplier { get; set; }

    public int ClubMultiplier { get; set; }

    public int? AccountMultiplier { get; set; }

    public bool? TicketAllowed { get; set; }

    public byte[] Image { get; set; }

    public Guid? ReportId { get; set; }
}