// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VTransaction
{
    public Guid Id { get; set; }

    public Guid TransactionId { get; set; }

    public Guid TransactionTypeId { get; set; }

    public Guid UserId { get; set; }

    public Guid? ViplevelId { get; set; }

    public Guid? VipcampaignId { get; set; }

    public Guid? PlayerId { get; set; }

    public DateTime Date { get; set; }

    public Guid? PaymentModalityId { get; set; }

    public Guid? ReferenceTypeId { get; set; }

    public Guid? ReferenceId { get; set; }

    public Guid? ReferenceItemId { get; set; }

    public Guid? ReferenceParentId { get; set; }

    public string ReferenceDescription { get; set; }

    public bool WithdrawAllowed { get; set; }

    public decimal? Value { get; set; }

    public decimal? Vipvalue { get; set; }

    public decimal? Sppvalue { get; set; }

    public decimal? AccountValue { get; set; }

    public decimal? TimeValue { get; set; }

    public string Note { get; set; }

    public Guid? TicketId { get; set; }

    public Guid? AccountTypeId { get; set; }

    public Guid? CurrencyId { get; set; }

    public DateTimeOffset? DateOffset { get; set; }

    public Guid? ServerId { get; set; }

    public string ExtraData { get; set; }

    public bool? Refunded { get; set; }

    public string Username { get; set; }

    public string UserDescription { get; set; }

    public string PlayerDescription { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}