// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VUser
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid? GroupId { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public bool System { get; set; }

    public bool Reserved { get; set; }

    public string IdentityCode { get; set; }

    public DateTime? BirthDate { get; set; }

    public int? Gender { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public Guid? CountryId { get; set; }

    public byte[] Photo { get; set; }

    public string Email { get; set; }

    public string Cell { get; set; }

    public string Phone { get; set; }

    public bool Disabled { get; set; }

    public decimal? DailyPay { get; set; }

    public int? TypeId { get; set; }

    public string Sid { get; set; }

    public DateTime? CreationDate { get; set; }

    public string ZipCode { get; set; }

    public string CardNumber { get; set; }

    public DateTime? CardExpiration { get; set; }

    public DateTime? LastUpdated { get; set; }

    public bool? Locked { get; set; }

    public int? FailedPasswordAttemptCount { get; set; }

    public DateTime? PasswordChange { get; set; }

    public DateTime? PasswordExpiration { get; set; }

    public int? FailedPasswordAttemptAllowed { get; set; }

    public bool? RequirePasswordExpiration { get; set; }

    public bool? RequirePasswordComplexity { get; set; }

    public int? PasswordValidityDays { get; set; }

    public bool? ForcePasswordChange { get; set; }

    public string GroupDescription { get; set; }

    public string CountryDescription { get; set; }

    public string CountryCode { get; set; }
}