// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VVendor
{
    public Guid Id { get; set; }

    public Guid VendorId { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string IdentityCode { get; set; }

    public string Vatid { get; set; }

    public DateTime? BirthDate { get; set; }

    public string City { get; set; }

    public string Address { get; set; }

    public string State { get; set; }

    public Guid? CountryId { get; set; }

    public byte[] Photo { get; set; }

    public string Email { get; set; }

    public string Cell { get; set; }

    public string Phone { get; set; }

    public string ZipCode { get; set; }

    public string SearchText { get; set; }

    public Guid ClubId { get; set; }

    public string ClubDescription { get; set; }
}