// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VVipsystem
{
    public Guid Id { get; set; }

    public Guid VipsystemId { get; set; }

    public Guid? SeasonId { get; set; }

    public Guid? SeasonLeagueId { get; set; }

    public decimal? PointPerBuyin { get; set; }

    public double? PointPerFee { get; set; }

    public decimal? PointPerHouse { get; set; }

    public decimal? PointPerTax { get; set; }

    public bool? IncludeRebuyFee { get; set; }

    public bool? IncludeAddonFee { get; set; }
}