// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VVipproduct
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public Guid VipproductId { get; set; }

    public Guid? VipcampaignId { get; set; }

    public Guid? ViplevelId { get; set; }

    public Guid? CategoryId { get; set; }

    public string Note { get; set; }

    public byte[] Image { get; set; }

    public int? TipologyId { get; set; }

    public Guid? ReferenceId { get; set; }

    public string ReferenceDescription { get; set; }

    public decimal? Spp { get; set; }

    public decimal? Value { get; set; }

    public DateTime? Expiration { get; set; }
}