// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VVippromotion
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid VippromotionId { get; set; }

    public decimal? PointsPerTournamentBuyin { get; set; }

    public decimal? PointsPerTournamentFee { get; set; }

    public decimal? PointsPerTournamentHouse { get; set; }

    public decimal? PointsPerTournamentTax { get; set; }

    public bool? IncludeTournamentRebuy { get; set; }

    public bool? IncludeTournamentAddon { get; set; }

    public DateTime? PointsExpiration { get; set; }

    public int? PointsExpirationDays { get; set; }

    public string TournamentFormula { get; set; }

    public string CashFormula { get; set; }

    public bool? IncludeTournamentRebuyAddon { get; set; }

    public Guid? ClubId { get; set; }
}