// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VVipcampaign
{
    public Guid Id { get; set; }

    public string Description { get; set; }

    public string SearchText { get; set; }

    public Guid VipcampaignId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public Guid? DefaultPromotionId { get; set; }

    public decimal? SppconversionMultiplier { get; set; }

    public decimal? VipconversionMultiplier { get; set; }

    public string Note { get; set; }

    public string Url { get; set; }

    public Guid? ClubId { get; set; }

    public string ClubDescription { get; set; }
}