// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VViptournament
{
    public Guid? PlayerId { get; set; }

    public decimal? Buyin { get; set; }

    public decimal? Fee { get; set; }

    public decimal? AddonAmount { get; set; }

    public decimal? AddonFee { get; set; }

    public decimal? RebuyAmount { get; set; }

    public decimal? RebuyFee { get; set; }

    public decimal? HouseAmount { get; set; }

    public decimal? RebuyHouseAmount { get; set; }

    public decimal? AddonHouseAmount { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? RebuyTaxAmount { get; set; }

    public decimal? AddonTaxAmount { get; set; }

    public Guid TournamentId { get; set; }

    public string ReferenceTypeId { get; set; }

    public Guid ReferenceId { get; set; }

    public Guid? ReferenceItemId { get; set; }

    public string ReferenceDescription { get; set; }

    public DateTime? Date { get; set; }

    public Guid? PromotionId { get; set; }
}