// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VVipcashSession
{
    public Guid? PlayerId { get; set; }

    public Guid? CashTypeId { get; set; }

    public decimal? Minutes { get; set; }

    public string ReferenceTypeId { get; set; }

    public Guid ReferenceId { get; set; }

    public Guid ReferenceItemId { get; set; }

    public string ReferenceDescription { get; set; }

    public DateTime? Date { get; set; }

    public Guid? PromotionId { get; set; }
}