// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VwApiTournamentRankingPerCountry
{
    public string CountryDescription { get; set; }

    public Guid TournamentId { get; set; }

    public string AuthorizationId { get; set; }

    public int? IngamePlayers { get; set; }

    public int? Points { get; set; }

    public int? TotalPlayers { get; set; }

    public int? TotalPoints { get; set; }

    public string Flag { get; set; }
}