// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VwReportTournament
{
    public Guid TournamentId { get; set; }

    public string AuthorizationId { get; set; }

    public Guid? TournamentParentId { get; set; }

    public string TournamentDescription { get; set; }

    public DateTime? StartDate { get; set; }

    public int? Behavior { get; set; }

    public bool? Addon { get; set; }

    public bool? Rebuy { get; set; }

    public bool KnockOut { get; set; }

    public int? TotalIngamePlayersCount { get; set; }

    public int? TotalPayoutsCount { get; set; }

    public bool TotalKnockOutsCount { get; set; }

    public int? TotalPlayersCount { get; set; }

    public int? ReEntries { get; set; }

    public decimal? TotalBuyin { get; set; }

    public decimal? TotalFee { get; set; }

    public decimal? TotalSubscription { get; set; }

    public decimal? TotalRebuyAddon { get; set; }

    public decimal? TotalRebuyAmount { get; set; }

    public decimal? TotalAddonAmount { get; set; }

    public decimal? TotalDoubleChanceAmount { get; set; }

    public decimal? TotalBuyinAmount { get; set; }

    public decimal? TotalFeeAmount { get; set; }

    public int? TotalRebuysCount { get; set; }

    public decimal? TotalRebuy { get; set; }

    public decimal? TotalRebuyFee { get; set; }

    public int? TotalAddonsCount { get; set; }

    public decimal? TotalAddon { get; set; }

    public decimal? TotalAddonFee { get; set; }

    public int? TotalDoubleChancesCount { get; set; }

    public decimal? TotalDoubleChance { get; set; }

    public decimal? TotalDoubleChanceFee { get; set; }

    public decimal? TotalKnockOut { get; set; }

    public decimal? TotalHouseContribution { get; set; }

    public decimal? TotalTax { get; set; }

    public decimal? TotalAdditional { get; set; }

    public decimal? TotalAmount { get; set; }

    public int? Status { get; set; }

    public decimal? TotalHouseContributionDefault { get; set; }

    public decimal? TotalHouseContributionLeague { get; set; }

    public double? TotalProfit { get; set; }

    public double? TotalOverlay { get; set; }

    public double? TotalAmountEffective { get; set; }

    public double? TotalProfitTax { get; set; }

    public double? TotalHouseContributionLeagueTax { get; set; }

    public Guid GameTypeId { get; set; }

    public string GameTypeDescription { get; set; }

    public Guid CurrencyId { get; set; }

    public string CurrencyDescription { get; set; }

    public string SeasonDescription { get; set; }

    public string SeasonLeagueDescription { get; set; }

    public Guid? ClubId { get; set; }
}