// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VwReportTournamentPlayer
{
    public Guid TournamentId { get; set; }

    public string Description { get; set; }

    public DateTime? StartDate { get; set; }

    public string AuthorizationId { get; set; }

    public Guid? ClubId { get; set; }

    public Guid TournamentPlayerId { get; set; }

    public Guid? PlayerId { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string Fullname { get; set; }

    public int? Status { get; set; }

    public bool Addon { get; set; }

    public int? RebuyCount { get; set; }

    public int? DoubleChanceCount { get; set; }

    public double? KnockOutCount { get; set; }

    public int? TournamentTableIndex { get; set; }

    public int? TournamentTableSitIndex { get; set; }

    public int? Ticket { get; set; }

    public DateTimeOffset? SubscriptionDate { get; set; }

    public string SubscriptionAuthorizationId { get; set; }

    public int? EliminationPosition { get; set; }

    public DateTimeOffset? EliminationDate { get; set; }

    public int? EliminationLevelIndex { get; set; }

    public int? EliminationTableIndex { get; set; }

    public int? EliminationTableSitIndex { get; set; }

    public long? EliminationLevelSeconds { get; set; }

    public int? EliminationDay { get; set; }

    public string EliminationGroup { get; set; }

    public int? Position { get; set; }

    public double? PayoutAmount { get; set; }

    public double? Points { get; set; }

    public double? LeaguePoints { get; set; }

    public double? ChipsCount { get; set; }

    public bool? ReEntry { get; set; }

    public bool? Punctuality { get; set; }

    public double? KnockOutAmount { get; set; }

    public double? KnockOutValue { get; set; }

    public bool? Qualified { get; set; }

    public string Email { get; set; }

    public string Cell { get; set; }

    public string Phone { get; set; }

    public string NickName { get; set; }

    public byte[] Photo { get; set; }

    public int? Gender { get; set; }

    public string CardNumber { get; set; }

    public DateTime? CardExpiration { get; set; }

    public string CountryCode { get; set; }

    public Guid? CountryId { get; set; }

    public string CountryDescription { get; set; }

    public byte[] Flag { get; set; }

    public string DayGroupDescription { get; set; }
}