// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VwReportPlayer
{
    public Guid PlayerId { get; set; }

    public string Fullname { get; set; }

    public string IdentityCode { get; set; }

    public int? Gender { get; set; }

    public DateTime? BirthDate { get; set; }

    public string City { get; set; }

    public string Address { get; set; }

    public string State { get; set; }

    public string ZipCode { get; set; }

    public string DocumentNumber { get; set; }

    public string Nickname { get; set; }

    public byte[] Photo { get; set; }

    public string Email { get; set; }

    public string Cell { get; set; }

    public string Phone { get; set; }

    public string CardNumber { get; set; }

    public DateTime? CardExpiration { get; set; }

    public Guid? CountryId { get; set; }

    public string CountryDescription { get; set; }

    public string Code { get; set; }

    public byte[] Flag { get; set; }
}