// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VwReportTournamentLevel
{
    public Guid TournamentLevelId { get; set; }

    public Guid TournamentId { get; set; }

    public int? LevelIndex { get; set; }

    public int? LevelType { get; set; }

    public double? Ante { get; set; }

    public double? SmallBlind { get; set; }

    public double? BigBlind { get; set; }

    public Guid? GameTypeId { get; set; }

    public string GameTypeDescription { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? ExpectedTime { get; set; }

    public double? TotalMinutes { get; set; }

    public int? OrderIndex { get; set; }
}