// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VwReportArticleFamily
{
    public Guid ArticleFamilyId { get; set; }

    public string ArticleFamilyDescription { get; set; }

    public string Path { get; set; }
}