// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VwReportTournamentPayout
{
    public Guid TournamentRateId { get; set; }

    public Guid TournamentId { get; set; }

    public int? Position { get; set; }

    public decimal? RateValue { get; set; }

    public Guid? PlayerId { get; set; }

    public string PlayerDescription { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string Email { get; set; }

    public string Cell { get; set; }

    public string Phone { get; set; }

    public Guid? CountryId { get; set; }

    public string CountryDescription { get; set; }

    public string CountryCode { get; set; }

    public byte[] Flag { get; set; }
}