// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VwReportTournamentPayment
{
    public DateTime Date { get; set; }

    public string TransactionDescription { get; set; }

    public decimal? Value { get; set; }

    public string Annotation { get; set; }

    public Guid? TournamentId { get; set; }

    public Guid? TournamentParentId { get; set; }

    public Guid TransactionTypeId { get; set; }

    public string TransactionTypeDescription { get; set; }

    public Guid PlayerId { get; set; }

    public string PlayerDescription { get; set; }

    public string Lastname { get; set; }

    public string Firstname { get; set; }

    public string Email { get; set; }

    public string Cell { get; set; }

    public string Phone { get; set; }

    public Guid? CountryId { get; set; }

    public string CountryDescription { get; set; }

    public string CountryCode { get; set; }

    public byte[] Flag { get; set; }

    public Guid? PaymentModalityId { get; set; }

    public int? PaymentTypeId { get; set; }

    public string PaymentModalityDescription { get; set; }

    public string UserFullname { get; set; }

    public string UserName { get; set; }

    public bool ReEntry { get; set; }

    public int? Ticket { get; set; }

    public int Rebuy { get; set; }

    public int Addon { get; set; }

    public int DoubleChance { get; set; }

    public int Payout { get; set; }

    public int Subscription { get; set; }
}