// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VwReportCounterSale
{
    public Guid DocumentId { get; set; }

    public DateTime? DocumentDate { get; set; }

    public int? DocumentNumber { get; set; }

    public Guid? ResourceId { get; set; }

    public string Fullname { get; set; }

    public double? Amount { get; set; }

    public double? PayedAmount { get; set; }

    public double? BonusAmount { get; set; }

    public double? CheckAmount { get; set; }

    public double? CashAmount { get; set; }

    public double? ChipsAmount { get; set; }

    public double? CreditCardAmount { get; set; }
}