// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class VwStatsTournamentPayment
{
    public Guid? TournamentId { get; set; }

    public Guid PaymentModalityId { get; set; }

    public decimal? Amount { get; set; }

    public int? Payments { get; set; }
}